# -*- coding: utf-8 -*-
"""Genera las dos versiones del briefing ciber-GRC desde un mismo contenido:
   1) briefing-ciber-grc.html  version rica para pantalla (claro y oscuro)
   2) briefing-correo.html     version apta para Gmail y Outlook (tablas + estilos en linea)
   Sin guiones largos en el texto."""

import re

SER = "Georgia,'Times New Roman',serif"
SAN = "Helvetica,Arial,sans-serif"

# paleta por seccion: (color, tinte claro, tinte oscuro, etiqueta)
SEC = {
 "es":  ("#C62828", "#FDECEA", "#3A1A18", "01. España: ENS, CCN y normativa nacional"),
 "eu":  ("#1565C0", "#E8F1FB", "#152534", "02. Unión Europea: regulación horizontal"),
 "fin": ("#00796B", "#E3F2F0", "#122B29", "03. Sector financiero: DORA y supervisores"),
 "std": ("#6A1B9A", "#F4E9F8", "#261830", "04. Normas y marcos de referencia"),
 "ai":  ("#E65100", "#FDEEE2", "#33200F", "05. Reglamento de IA, datos y sanciones"),
 "thr": ("#AD1457", "#FCE9F1", "#331522", "06. Amenaza y exposición"),
}
SEC_DARK = {"es":"#F08A80","eu":"#7FB0F5","fin":"#4FC9B8","std":"#C39BF0","ai":"#F2A25C","thr":"#F08BB4"}

HOT, HOTBG = "#C62828", "#FDECEA"


# ══════════ IDENTIDAD DE LA EDICIÓN (lo lee la plantilla, no lo dupliques) ══════════
NUM        = 6
FECHA_ISO  = "2026-09-28"
FECHA_TXT  = "28 de septiembre de 2026"
PERIODO    = "del 21 al 28 de septiembre de 2026"

TITULAR = "Citrix cierra la semana con dos días cero explotados, y el BCE avisa de que los planes del 31 de octubre se van a comparar unos con otros"
ENTRADA = ("Semana densa en lo operativo y reveladora en lo supervisor. El domingo 27 Citrix reconoció explotación activa de dos "
 "vulnerabilidades sin autenticación en NetScaler, y el catálogo estadounidense de vulnerabilidades explotadas les puso el plazo "
 "más corto del año, tres días; el INCIBE-CERT publicó su aviso esta misma mañana. En supervisión, la presidenta del Consejo de "
 "Supervisión del BCE dijo el 22 en Ámsterdam lo que la carta de julio no decía tan claro: los planes contra la ciberamenaza "
 "potenciada por IA que vencen el 31 de octubre se evaluarán en horizontal, es decir, comparados entre entidades. En Bruselas se "
 "abre hasta el 13 de octubre la única ventana real de enmiendas del paquete que reabre NIS2. Y en España, Adif y Renfe "
 "confirmaron un acceso con datos de clientes, mientras el Congreso deja el 30 de septiembre en pie sin nueva prórroga.")

CLAVE_1 = ("Lo más urgente es de anoche. El <b>27 de septiembre</b> Citrix publicó un boletín con ocho vulnerabilidades en NetScaler "
 "ADC y NetScaler Gateway y escribió que se han observado explotaciones de <b>CVE-2026-88771</b> y <b>CVE-2026-88772</b> en "
 "despliegues sin mitigar. La primera permite a un atacante <b>sin autenticar</b> ejecutar órdenes arbitrarias. Ese mismo día "
 "entraron en el catálogo KEV con fecha límite el <b>30 de septiembre</b>: tres días, el plazo más corto que se ha visto este año, "
 "y bajo una directiva estadounidense que exige además triaje forense, no solo parchear. Hoy, <b>28 de septiembre</b>, el "
 "INCIBE-CERT ha publicado el aviso <b>INCIBE-2026-667</b>, que recoge los ocho y confirma la explotación de los dos primeros. No "
 "es un caso aislado: en la misma semana Check Point, F5 y Arista han reconocido explotación activa en producto de perímetro.")

CLAVE_2 = ("La señal de fondo es supervisora. El <b>22 de septiembre</b>, en Ámsterdam, la presidenta del Consejo de Supervisión del "
 "BCE contó en público el ejercicio que abrió la carta del 7 de julio y añadió algo que esa carta decía con menos filo: los planes "
 "de acción «se evaluarán en horizontal para identificar y compartir buenas prácticas». Traducido: el plan de cada entidad no se "
 "lee solo, se lee al lado de los de sus pares, y quedan <b>treinta y tres días</b> hasta el <b>31 de octubre</b>. En paralelo, el "
 "Comité Mixto de las tres autoridades europeas de supervisión publicó el 23 su informe de otoño, que sitúa la dependencia de "
 "proveedores TIC de fuera del Espacio Económico Europeo y los ataques potenciados por IA como la vulnerabilidad principal del "
 "sistema financiero. Y en Bruselas, la comisión de Industria del Parlamento abrió hasta el <b>13 de octubre</b> el plazo de "
 "enmiendas a los dos proyectos de informe que reabren NIS2 y el Reglamento de Ciberseguridad.")

PLAZOS = [
 ("29 sep 2026", True,  "Audiencia pública de la EBA sobre las RTS de gestión del riesgo operacional, de 10:00 a 12:00; la inscripción cerró el 25", "Bancos"),
 ("30 sep 2026", True,  "Cierre de los plazos de enmiendas de 121/000088 (entidades críticas), 121/000105 (adaptación de DORA), 121/000096 (ley orgánica de IA) y 121/000068, según el cuadro del Congreso del 25 de septiembre, que no trae nueva prórroga", "Quien quiera influir en cualquiera de los textos españoles"),
 ("30 sep 2026", True,  "Fecha límite del catálogo KEV para las dos vulnerabilidades explotadas de Citrix NetScaler; no obliga en España, pero fija el listón de diligencia", "Cualquiera con NetScaler como pasarela o servidor virtual de autenticación"),
 ("1 oct 2026",  True,  "Entrada en vigor de la NISG austriaca, con notificación de incidentes obligatoria desde ese mismo día", "Grupos españoles con filiales o servicios en Austria"),
 ("1 oct 2026",  True,  "Seminario del CCN sobre PILAR Web, de 11:30 a 12:30, con el nuevo procedimiento de registro y licencias", "Quien use PILAR en adecuaciones al ENS"),
 ("5 oct 2026",  True,  "Cierre de comentarios del NIST IR 8613 sobre seguridad y cumplimiento en arquitecturas multinube", "Quien quiera posicionarse en el debate de multinube"),
 ("7 oct 2026",  True,  "Discusión en sesión pública, en la Asamblea Nacional francesa, del proyecto de resiliencia que transpone NIS2 y CER", "Grupos con filial en Francia y quien siga el mapa de transposición"),
 ("13 oct 2026", True,  "Cierre del plazo de enmiendas en la comisión de Industria del Parlamento Europeo a los dos proyectos de informe: modificación de NIS2 y revisión del Reglamento de Ciberseguridad", "Asociaciones sectoriales que quieran influir en el paquete"),
 ("15 oct 2026", True,  "Cierre de comentarios del NIST SP 1353 sobre el uso de IA para analizar el marco de ciberseguridad", "Despachos y consultoras con práctica de IA y cumplimiento"),
 ("30 oct 2026", False, "Cierre de las consultas del CEPD sobre anonimización (02/2026) y sobre web scraping para IA generativa (03/2026)", "Cualquiera que confíe en datos anonimizados o entrene modelos con datos web"),
 ("30 oct 2026", False, "Cierre de la encuesta NIS360 de ENISA, que devuelve informe de comparación con los pares del sector", "Entidades esenciales e importantes de los sectores del anexo I"),
 ("31 oct 2026", False, "Plan de acción sobre ciberamenaza potenciada por IA al Equipo Conjunto de Supervisión", "Todas las entidades significativas del MUS"),
 ("13 nov 2026", False, "Cierre de la consulta del CEPD sobre las directrices de cálculo y uso de las multas", "Responsables y asociaciones que quieran opinar sobre cómo se sanciona"),
 ("21 nov 2026", False, "Fin aproximado del escrutinio del Parlamento y el Consejo sobre el reglamento delegado de calificación de centros de datos, adoptado el 21 de septiembre", "Quien opere o contrate centros de datos de más de 500 kW"),
 ("30 nov 2026", False, "Cierre de comentarios del NIST SP 800-82 Rev. 4, la guía de seguridad de tecnología operativa", "Industria, energía, agua y transporte"),
 ("2 dic 2026",  False, "Los sistemas de IA generativa comercializados antes del 2 de agosto de 2026 deben cumplir el marcado del artículo 50.2", "Proveedores de sistemas generativos y de contenido sintético"),
 ("11 dic 2026", False, "Los Estados deben tener notificados organismos de evaluación de la conformidad suficientes para el CRA", "Fabricantes de productos importantes y críticos con elementos digitales"),
 ("14 dic 2026", False, "Cierre de la consulta de la Comisión sobre normas mínimas de rendimiento para centros de datos en Europa", "Operadores de centros de datos y grandes contratantes de alojamiento"),
 ("31 dic 2026", False, "Cierre de la consulta de la EBA sobre las RTS de riesgo operacional", "Bancos"),
 ("1 ene 2027",  False, "Aplicación de las Directrices SREP revisadas de la EBA, con el riesgo TIC dentro del examen supervisor", "Bancos y entidades supervisadas por el Banco de España y el MUS"),
 ("1 ene 2027",  False, "Fin del plazo de registro inicial de entidades bajo la NISG austriaca", "Grupos españoles con filiales en Austria"),
 ("2 dic 2027",  False, "Obligaciones de alto riesgo del anexo III del Reglamento de IA, tras el aplazamiento del Reglamento 2026/1744", "Proveedores y responsables del despliegue de IA de alto riesgo"),
 ("11 dic 2027", False, "Requisitos esenciales y evaluación de conformidad del CRA plenamente aplicables", "Fabricantes de productos con elementos digitales"),
]

# titulares de las tarjetas de portada, uno por ámbito
TITS = {
 "es":  "El cuadro del Congreso del 25 de septiembre no prorroga nada, y el 30 sigue en pie para los cuatro proyectos",
 "eu":  "La comisión de Industria abre hasta el 13 de octubre la única ventana de enmiendas del paquete que reabre NIS2",
 "fin": "El BCE avisa de que los planes del 31 de octubre se evaluarán en horizontal, unos frente a otros",
 "std": "El NIST deja dos plazos venciendo en octubre y la acreditación de la 42001 sigue sin llegar a España",
 "ai":  "La AEPD advierte a una empresa antes de que despliegue IA para cribar currículums",
 "thr": "Dos días cero de Citrix explotados, con el plazo más corto del año en el catálogo KEV",
}

# (seccion, marcas, prioritario, titular, que_cambia, por_que, que_leer, aviso)
ITEMS = [
("es", "Congreso · cuadro del 25 de septiembre", True,
 "El cuadro del Congreso deja de prorrogar por primera vez en meses, y el 30 de septiembre sigue en pie para los cuatro proyectos",
 "El cuadro de plazos de enmiendas, <b>actualizado el viernes 25 de septiembre de 2026</b>, mantiene el <b>30 de septiembre</b> como último día para los cuatro textos del ámbito y <b>no trae ninguna prórroga nueva</b>: el <b>121/000088</b> de protección y resiliencia de las entidades críticas, que transpone CER, en plazo desde el 17 de abril y con dieciséis fechas encadenadas; el <b>121/000105</b> de digitalización y modernización del sector financiero, que adapta DORA, con cuatro; el <b>121/000096</b>, ley orgánica de buen uso y gobernanza de la IA, con seis; y el <b>121/000068</b>, de gobernanza democrática en servicios digitales y medios, que lleva prorrogándose sin interrupción desde el 17 de septiembre de 2025. En el BOCG sigue sin haber enmiendas, ponencia ni dictamen de ninguno de los cuatro: solo existe el texto del proyecto.",
 "Hay que trabajar como si el miércoles fuera el último día, pero sin dar por hecho que lo sea: la Mesa se reúne los martes, así que una prórroga acordada el 29 no aparecería en el cuadro del 25. Quien tenga una nota técnica para un grupo parlamentario sobre el perímetro de entidades críticas, el régimen sancionador financiero o las competencias de la AESIA, la envía ahora. Y el mensaje al cliente que pregunta cuándo le aplica: nadie lo sabe, y mientras tanto lo que obliga es el Reglamento, no la ley española. El 088 y el 105 van por competencia legislativa plena, así que el texto no vuelve al Pleno, y el 105 va además por urgencia.",
 '<a href="https://www.congreso.es/webpublica/ficherosportal/cuadro_plazo_enmiendas_XV.pdf" @L>Cuadro de plazos de enmiendas del Congreso, actualizado el 25 de septiembre</a>.',
 "Que no haya enmiendas publicadas se apoya en que en el BOCG solo existe el documento 1 de cada expediente, comprobado uno a uno; no se ha podido abrir la ficha de tramitación individual de ninguno. Conviene volver a descargar el cuadro el viernes 2 de octubre."),

("es", "CCN · 22 sep 2026", False,
 "El lema de las Jornadas STIC dice hacia dónde va el CCN: IA ofensiva y amenaza cuántica, y el formulario de INES ya venció",
 "El <b>22 de septiembre</b> el CCN comunicó haber recibido <b>más de 370 propuestas</b> de ponencia para las <b>XX Jornadas STIC</b>, en Madrid del <b>24 al 27 de noviembre de 2026</b>, bajo el lema «IA ofensiva y amenaza cuántica: hacia una nueva ciberseguridad». Es lo único publicado por el canal oficial del CCN-CERT en la ventana. En paralelo, el formulario de autoevaluación sobre IA ofensiva de INES <b>venció el 21 de septiembre</b> sin que conste una segunda ampliación: la última entrada de actualidad del CCN es del 17 y la del canal oficial, la del 22. Sigue en pie el seminario de <b>PILAR Web</b> del <b>1 de octubre</b>, de 11:30 a 12:30, con el nuevo procedimiento de registro y licencias.",
 "El lema no es decoración: es la lista de la compra del regulador técnico español para los próximos dos años, y coincide con el formulario de INES y con la carta del BCE. Si un cliente en ámbito ENS no tiene todavía un inventario criptográfico ni un plan de migración poscuántica, ya hay señal suficiente para ponerlo en el plan del ejercicio que viene. Sobre el formulario, si alguien no llegó, lo razonable es dejar constancia del motivo y del plan para completarlo, porque sus resultados tienen que revisarse en el Comité de Seguridad de la Información e integrarse en el análisis de riesgos. Y del seminario interesa sobre todo el cambio de licencias, que es lo que puede parar un proyecto a mitad.",
 '<a href="https://t.me/s/CCNCERT" @L>Canal oficial del CCN-CERT</a> y la <a href="https://www.ccn.cni.es/es/actualidad-ccn" @L>página de actualidad del CCN</a>.',
 "Que el formulario no se haya vuelto a ampliar es «no consta ampliación», no «el CCN ha confirmado el cierre»: la web del CCN-CERT sigue bloqueando el acceso automatizado y el dato se apoya en el canal de Telegram y en la actualidad del CCN. No se ha podido abrir el portal ÁNGELES para confirmar que la inscripción al seminario siga abierta."),

("eu", "Parlamento Europeo · 18 y 24 sep 2026", True,
 "La comisión de Industria publica los dos proyectos de informe que reabren NIS2 y el Reglamento de Ciberseguridad, con enmiendas hasta el 13 de octubre",
 "Dos documentos de la ponente <b>Markéta Gregorová</b>. El <b>18 de septiembre</b>, el proyecto de informe sobre el reglamento que sustituye al de Ciberseguridad y deroga el Reglamento 2019/881 (referencia <b>PE792.222v01-00</b>, procedimiento <b>2026/0011</b>). El <b>24 de septiembre</b>, el proyecto de informe sobre la directiva que <b>modifica NIS2</b> con medidas de simplificación y alineamiento (referencia <b>PE792.221v02-00</b>, procedimiento <b>2026/0012</b>), que sale ya en segunda versión. Los dos llevan el mismo <b>plazo de enmiendas: 13 de octubre de 2026</b>.",
 "Es la primera vez que el Parlamento pone texto propio encima de la mesa en el paquete que reabre NIS2, y ese plazo de quince días naturales es la única ventana real de influencia antes del voto en comisión y del trílogo. Quien tenga posición sectorial, la hace llegar ahora a través de un eurodiputado o de su asociación. Ojo con el detalle que se confunde: el procedimiento de NIS2 es el 2026/0012 y el del Reglamento de Ciberseguridad el 2026/0011, no al revés. No es texto aprobado, así que sirve para anticipar la conversación con el cliente, no para planificar sobre ella.",
 '<a href="https://www.europarl.europa.eu/committees/en/itre/documents/latest-documents" @L>Documentos recientes de la comisión ITRE</a>.',
 "Se han verificado referencias, fechas, ponente y plazo en la página oficial de la comisión, pero <b>no se ha podido abrir el contenido</b> de ninguno de los dos proyectos de informe: el registro documental del Parlamento bloquea el acceso automatizado. No se puede decir aún qué propone la ponente, ni qué cambió entre la primera y la segunda versión del de NIS2."),

("eu", "Comisión Europea · 25 sep 2026", False,
 "El paquete de infracciones de septiembre no toca ciberseguridad, y a España se la emplaza por la sexta directiva antiblanqueo",
 "El <b>25 de septiembre</b> la Comisión publicó su paquete de cartas de emplazamiento por no comunicar transposiciones (referencia <b>INF/26/1834</b>). Se ha leído íntegro: <b>no contiene ni una sola mención a NIS2, CER, DORA ni al CRA</b>. Los ocho bloques son mercado eléctrico, hidrógeno y gas descarbonizado, <b>sexta directiva antiblanqueo</b>, cobalto en juguetes, trata de seres humanos, nuevas sustancias psicoactivas, derecho a reparar y emisiones industriales. España aparece emplazada en cinco de ellos, incluido el antiblanqueo, junto con otros diecisiete Estados.",
 "Este es un resultado negativo comprobado, no una ausencia de búsqueda, y por eso vale: en septiembre no se abrió ni escaló ningún procedimiento nuevo de ciberseguridad horizontal. Lo que sí se movió toca a clientes financieros por otra vía, la del antiblanqueo. Y conviene actualizar el marcador: la base de decisiones de infracción ha cambiado de dirección y la antigua devuelve error, cosa que explica bastantes «no se ha localizado paquete» de semanas anteriores.",
 '<a href="https://ec.europa.eu/commission/presscorner/detail/en/inf_26_1834" @L>Paquete de infracciones INF/26/1834</a>.',
 "El barrido de referencias del tipo INF en todo el rango de la ventana solo devuelve dos documentos en lo que va de julio a septiembre, así que la afirmación es sólida para ese prefijo; no se puede descartar al cien por cien un comunicado con otro prefijo."),

("eu", "ENISA · 22 sep 2026", False,
 "El panorama de amenazas de ENISA pone número a algo que se sospechaba: tres de cada cuatro entidades atacadas están en el perímetro de NIS2",
 "El <b>22 de septiembre</b> ENISA publicó el <b>ENISA Threat Landscape 2026</b>, con datos de incidentes del <b>1 de enero al 31 de diciembre de 2025</b>, un año natural completo (la edición anterior usaba otra ventana, así que las series no son directamente comparables). Las cifras que importan: las entidades esenciales e importantes de NIS2 representan el <b>73%</b> de los eventos registrados; el sector más golpeado es la <b>administración pública, con el 31,8%</b>, seguida de servicios a empresas (8,5%), transporte (8%), fabricación (6,9%) y finanzas y banca (5,6%); el <b>51,3%</b> de los incidentes son denegaciones de servicio distribuidas de bajo impacto y el 39,5% accesos no autorizados; y en 2025 se publicaron <b>más de 48.000</b> vulnerabilidades con identificador, un <b>22%</b> más que el año anterior.",
 "Es la munición estadística oficial de la Unión para lo que queda de año, y sirve para dos conversaciones distintas. Con un consejo de administración, el 73% convierte el perímetro de NIS2 de trámite jurídico en hecho empírico. Con un equipo técnico, el matiz importa más: si la mitad del volumen es denegación de servicio de bajo impacto, el ruido de los cuadros de mando no debe desplazar la atención del 39,5% de accesos no autorizados, que es donde está el daño. Y el informe converge con el NIS360 al señalar los mismos sectores con madurez por debajo de la media y criticidad por encima: salud, ferrocarril, marítimo, gestión de servicios TIC, espacio, administración pública y agua.",
 '<a href="https://www.enisa.europa.eu/publications/enisa-threat-landscape-2026" @L>ENISA Threat Landscape 2026</a>.',
 None),

("eu", "Transposición · Francia, Austria y el mapa", False,
 "Francia fija por fin fecha de pleno, el 7 de octubre, y Austria empieza a exigir el 1; España sigue siendo el único Estado a cero en las dos directivas",
 "<b>Francia</b>: el expediente oficial de la Asamblea Nacional ya recoge la <b>discusión en sesión pública para el miércoles 7 de octubre de 2026</b>, sobre el texto de la comisión especial de septiembre de 2025. Con procedimiento acelerado, tras el voto pasa a comisión mixta paritaria, no a segunda lectura. <b>Austria</b>: la ventanilla oficial confirma que la NISG 2026 entra en vigor el <b>1 de octubre</b>, que notificar incidentes es obligatorio <b>desde ese mismo día</b> y que el registro inicial debe completarse antes del <b>1 de enero de 2027</b>. Y el dato que ordena el mapa: en medidas nacionales notificadas, solo <b>Irlanda y España</b> están a cero en NIS2, y <b>Bulgaria, España y Suecia</b> en CER. <b>España es el único a cero en las dos</b>.",
 "Lo de Austria es lo accionable del miércoles: un grupo español con filial austriaca queda obligado a notificar desde el día 1 aunque aún no se haya registrado, así que el procedimiento tiene que estar listo antes que el alta. Lo de Francia es argumento: si la Asamblea vota el 7, Francia puede cerrar transposición a caballo entre 2026 y 2027, y España se queda con Irlanda como única compañía en NIS2 y sola en la intersección de las dos. Y una advertencia de método para no equivocarse al leer la tabla de medidas notificadas: Francia figura con decenas de medidas y sigue sin transponer, porque lo notificado es el andamiaje anterior. Contar medidas no mide cumplimiento.",
 '<a href="https://www.assemblee-nationale.fr/dyn/17/dossiers/DLR5L17N50731" @L>Expediente del proyecto francés de resiliencia</a> y la <a href="https://www.usp.gv.at/aktuelles/newsliste/NIS-2.html" @L>nota de la ventanilla austriaca sobre NIS2</a>.',
 "La fecha francesa sale del expediente oficial, no del orden del día confirmado de la Conferencia de Presidentes, que no se pudo abrir: las sesiones se reordenan. Y sobre si hubo notificaciones nuevas en la ventana, la tabla de medidas nacionales no publica fecha de notificación ni de alta, solo la del acto nacional, así que ahí es «no verificable», no «no hubo»."),

("eu", "Nube y soberanía digital", False,
 "El reglamento de calificación de centros de datos está adoptado, no publicado, y ahora empieza el escrutinio de dos meses",
 "Precisión sobre lo que contamos la semana pasada. El <b>21 de septiembre</b> la Comisión <b>adoptó</b> el reglamento delegado que crea el esquema común de calificación de centros de datos de la Unión, pero <b>no está publicado en el DOUE</b>: queda sujeto a un <b>periodo de escrutinio de dos meses</b> del Parlamento y el Consejo, que pueden objetar pero no enmendar, y que termina hacia el 21 de noviembre. Cubre centros de datos individuales de <b>más de 500 kW</b>, mide energía, agua y contribución a la red, y prevé las primeras etiquetas en <b>2027</b> y una primera revisión a <b>finales de 2028</b>. En paralelo sigue abierta hasta el <b>14 de diciembre</b> la consulta sobre <b>normas mínimas de rendimiento</b> para centros de datos. La Comisión escribe que la Unión quiere <b>triplicar</b> su capacidad de centros de datos en cinco a siete años.",
 "La diferencia entre adoptado y publicado no es pedantería: el texto todavía puede decaer por objeción, y la fecha de aplicación se cuenta desde la publicación, no desde el 21 de septiembre. Para un cliente que opera o contrata alojamiento, lo que hay que fijar hoy es el umbral de 500 kW, que decide quién entra, y apuntar la consulta de diciembre, que es la que puede convertir la transparencia en mínimos obligatorios. Es normativa energética, no de seguridad, pero cae sobre la misma infraestructura que DORA mira por riesgo de concentración. De la propuesta de reglamento de desarrollo de la nube y la IA no hay novedad en la ventana, y del esquema europeo de certificación de nube, tampoco: su última noticia es del 10 de agosto.",
 '<a href="https://ec.europa.eu/commission/presscorner/detail/en/ip_26_1667" @L>Nota de la Comisión sobre el esquema de calificación de centros de datos</a>.',
 "Corrección a la edición 005: dijimos que la Comisión «publicó» el reglamento delegado el 21 de septiembre. Lo adoptó. En el DOUE, el único acto de esta materia sigue siendo el Reglamento Delegado (UE) 2024/1364 de la primera fase."),

("fin", "BCE · 22 sep 2026", True,
 "El BCE dice en público lo que la carta de julio no decía tan claro: los planes del 31 de octubre se van a evaluar en horizontal",
 "El <b>22 de septiembre</b>, en la conferencia anual de la asociación de banca extranjera de los Países Bajos, en Ámsterdam, la presidenta del Consejo de Supervisión pronunció el discurso «Digital innovation: hindrance or booster for banks' business models?». El pasaje relevante: los modelos frontera de IA han aumentado la velocidad y la escala con que se identifican y explotan vulnerabilidades, «este verano pedimos a los bancos que reevaluaran sus defensas y presentaran planes de acción concretos», y esos planes «<b>se evaluarán en horizontal para identificar y compartir buenas prácticas</b>». La carta del <b>7 de julio</b> fija el envío al Equipo Conjunto de Supervisión el <b>31 de octubre de 2026</b> y ya anunciaba un análisis horizontal. Otros datos del discurso: alrededor de <b>dos tercios</b> de los bancos de la zona del euro tienen acuerdos con proveedores de nube externos, a menudo fuera de la Unión; más del <b>90%</b> integran IA y el <b>85%</b> usan IA generativa.",
 "Quedan <b>treinta y tres días</b>, y el matiz cambia cómo se escribe el plan. Si se evalúa en horizontal, el plan de cada entidad se lee al lado del de sus pares: un documento genérico no queda simplemente aprobado o no, queda comparado, y destaca por abajo. Lo que aguanta esa lectura es el plan que conecta con el marco de riesgo TIC de DORA, lleva responsables y fechas, trata la velocidad del atacante y dice qué se deja para después y por qué. Y el dato de la nube da el segundo frente: si dos tercios dependen de proveedores a menudo extracomunitarios, la estrategia de salida deja de ser un anexo contractual.",
 '<a href="https://www.bankingsupervision.europa.eu/press/speeches/date/2026/html/ssm.sp260922~6d21ed7918.en.html" @L>Discurso del 22 de septiembre</a> y la <a href="https://www.bankingsupervision.europa.eu/press/letterstobanks/shared/pdf/2026/ssm.2026_letter_on_AI_enabled_cybersecurity_threats.en.pdf" @L>carta del 7 de julio sobre ciberamenazas potenciadas por IA</a>.',
 "El discurso no menciona la fecha límite; el 31 de octubre está verificado sobre el PDF de la carta, no sobre el discurso. En la ventana no hay carta nueva, ni consulta abierta, ni número de septiembre del boletín de supervisión."),

("fin", "AES · 23 sep 2026", True,
 "Las tres autoridades europeas de supervisión ponen la dependencia de proveedores TIC de fuera del Espacio Económico Europeo como vulnerabilidad principal",
 "El <b>23 de septiembre</b> el Comité Mixto de la EBA, ESMA y EIOPA publicó su informe conjunto de riesgos y vulnerabilidades del sistema financiero de la Unión, de otoño de 2026 (referencia <b>JC 2026 29</b>). Escribe que la alta dependencia de proveedores TIC terceros y de proveedores de servicios de pago amplifica el riesgo operativo, que esos proveedores están a menudo domiciliados fuera de la Unión, y que en la encuesta de la EBA sobre dependencias extracomunitarias los bancos señalan las de proveedores TIC como su mayor reto, en torno al <b>80%</b>, y las de soluciones de pago como el segundo riesgo material, en torno al <b>60%</b>. Sobre IA: los modelos frontera «pueden identificar y explotar vulnerabilidades informáticas a velocidad y escala», con efecto en la siniestralidad y la acumulación de las pólizas de ciber. Entre las acciones recomendadas, vigilar las dependencias en el contexto de los equipos conjuntos de vigilancia de DORA e incorporar pruebas de seguridad asistidas por IA.",
 "Este documento marca de hecho la agenda supervisora del semestre, y deja dos ganchos concretos. El primero: revisar el registro de información de DORA del cliente por el ángulo de la <b>concentración fuera del Espacio Económico Europeo</b>, no solo por criticidad, que es como suele estar montado. El segundo: si las autoridades escriben que las pruebas de seguridad asistidas por IA son práctica esperable, eso entra en la conversación de pruebas de resiliencia y de red team antes de lo que parecía. Y para quien asesore en seguro de ciber, la mención a la acumulación de siniestros es la que hay que llevar a la renovación.",
 '<a href="https://www.eba.europa.eu/publications-and-media/press-releases/esas-call-vigilance-over-external-dependencies-cyber-threats-and-private-credit-risks" @L>Nota conjunta de las tres autoridades del 23 de septiembre</a>.',
 "Las dos cifras de la encuesta se han leído del PDF del informe y se dan como aproximadas, tal y como las escribe el propio documento."),

("fin", "EBA · precisión sobre las directrices de terceros", False,
 "Las directrices de riesgo de terceros no TIC ya tienen número, EBA/GL/2026/09, pero siguen sin fecha de aplicación",
 "Precisión sobre lo que contamos la semana pasada, ahora leída sobre el informe final. Las directrices de gestión del riesgo de terceros en <b>servicios no TIC</b> llevan número <b>EBA/GL/2026/09</b> y portada de <b>18 de septiembre de 2026</b>; el informe final aparece en el listado de publicaciones de la EBA el <b>21</b>. La fecha de aplicación <b>sigue en blanco</b>: el texto dice literalmente que se aplican «desde [fecha]» y que las directrices de externalización de 25 de febrero de 2019 «quedan derogadas con efectos desde [fecha]», con la misma marca de posición en el plazo para que los supervisores comuniquen si las cumplen. El <b>periodo transitorio de dos años</b> se cuenta desde esa fecha de aplicación. Los destinatarios son entidades de crédito, empresas de servicios de inversión, entidades de pago y de dinero electrónico, emisores de fichas referenciadas a activos y prestamistas que sean entidades financieras.",
 "La consecuencia práctica es que <b>todavía no corre ningún reloj</b>, y eso es exactamente lo que hay que decirle al cliente que pregunta cuándo tiene que estar listo: la respuesta honesta es que no se puede calcular, porque depende de la publicación de las traducciones. Lo que sí se puede hacer ya, y conviene, es el trabajo de diseño: un único inventario de terceros con dos lentes, DORA para lo TIC y estas directrices para el resto, y un criterio único de función crítica o importante. Mientras tanto, las directrices de externalización de 2019 siguen plenamente vigentes.",
 '<a href="https://www.eba.europa.eu/publications-and-media/press-releases/eba-publishes-its-final-guidelines-management-third-party-risk-delivering-more-proportionate-and" @L>Nota de prensa y el informe final de la EBA</a>.',
 "El informe final no cita literalmente el número EBA/GL/2019/02 de las directrices que deroga: las identifica por su fecha, 25 de febrero de 2019."),

("fin", "ESMA y proveedores críticos · 23 sep 2026", False,
 "ESMA suma una prioridad supervisora de innovación digital para 2027, y la de ciberresiliencia se queda donde estaba",
 "El <b>23 de septiembre</b> ESMA anunció una nueva prioridad supervisora de la Unión sobre <b>innovación digital</b>, que arranca en <b>2027</b> y cuyo foco inicial serán <b>la inteligencia artificial y la tokenización</b>. La nota dice expresamente que la nueva prioridad «correrá en paralelo con la de ciberseguridad y resiliencia operativa, vigente desde 2025»; la que se cierra este año es la de divulgación en materia ambiental, social y de gobernanza. Por separado, en proveedores TIC críticos de DORA <b>no ha habido designaciones ni bajas</b>: la lista sigue siendo la de <b>19</b> proveedores publicada el <b>18 de noviembre de 2025</b>, y la actualización anual que prevé el artículo 31.8 tocaría hacia noviembre.",
 "Conviene leerlo como acumulación, no como relevo: a partir de 2027 un supervisor de valores puede preguntar por ciberresiliencia y por gobierno de la IA en la misma visita, y son marcos distintos. Para quien prepare a una gestora o a una empresa de servicios de inversión, el inventario de casos de uso de IA deja de ser un ejercicio interno y pasa a ser material supervisor. Y sobre los proveedores críticos, que la lista no se mueva es útil de saber: si un cliente esperaba que su proveedor entrara o saliera, no ha pasado, y la ventana realista es noviembre.",
 '<a href="https://www.esma.europa.eu/press-news/esma-news/esma-sets-new-supervisory-priority-digital-innovation-2027" @L>Nota de ESMA del 23 de septiembre</a>.',
 "La sala de prensa de la CNMV devolvió acceso denegado toda la semana y las novedades de la DGSFP no se pudieron abrir, así que en supervisores españoles es «no alcanzado» y no «sin novedad». El PDF de la lista de proveedores críticos no lleva fecha impresa: la vigencia se deduce de la ruta del fichero."),

("std", "NIST · plazos de octubre", False,
 "Dos plazos del NIST vencen en octubre, y el de centros de datos de IA se cerró el 25 de septiembre",
 "Estado de los borradores abiertos, comprobado ficha a ficha. <b>Cerrado</b>: la <b>SP 800-239</b>, sobre seguridad de centros de datos de IA, cuyos comentarios vencieron el <b>25 de septiembre</b>; sigue en borrador inicial. <b>Vivos</b>: la <b>IR 8613</b>, sobre retos de seguridad y cumplimiento en arquitecturas multinube, hasta el <b>5 de octubre</b>, con veintitrés áreas de reto y brechas señaladas en gestión de identidades, registro y telemetría, gestión de configuración, protección de datos y autorización; la <b>SP 1353</b>, hasta el <b>15 de octubre</b>; y la <b>SP 800-82 Rev. 4</b> de tecnología operativa, hasta el <b>30 de noviembre</b>. La <b>IR 8547</b>, la del calendario poscuántico, sigue en el borrador inicial de noviembre de 2024, sin versión final.",
 "Una precisión que cambia a quién se le enseña cada documento: la SP 1353 no trata de gobernar la IA, sino de <b>usar IA para analizar el marco de ciberseguridad y elaborar informes</b>, con prompts estructurados y tres casos de uso. Es material de productividad para el analista de cumplimiento, no de control de modelos, y confundirlo lleva a llevárselo al comité equivocado. La IR 8613 es la que más rinde a corto plazo, porque casi todo cliente mediano tiene ya dos nubes y ninguna respuesta ordenada a cómo se unifican identidades y registro entre ellas. Ninguna de las cuatro es normativa europea: son posicionamiento y buenas prácticas.",
 '<a href="https://csrc.nist.gov/pubs/ir/8613/ipd" @L>NIST IR 8613</a> y <a href="https://csrc.nist.gov/pubs/sp/1353/ipd" @L>NIST SP 1353</a>.',
 None),

("std", "ISO y acreditación · 25 sep 2026", False,
 "La norma de vocabulario de la familia 27000 se renovó en julio, y la acreditación de la 42001 sigue sin existir en España",
 "Dato que conviene incorporar aunque sea anterior a la ventana: la <b>ISO/IEC 27000</b> tiene <b>sexta edición, publicada el 3 de julio de 2026</b>, que retira la de 2018. Es la norma de vocabulario y visión general de toda la familia. En el resto, sin cambios en la ventana: la 27001 con su enmienda de 2024, la 27701:2025, la 42001, la 42005 y la 42006 siguen publicadas y estables; la 27002 y la 27005 están en revisión sistemática abierta. En acreditación, <b>ENAC sigue sin tener la 42001</b> entre sus esquemas de sistemas de gestión, que continúan siendo 9001, 14001, 22000, 27001 y 50001; lo que sí hizo el <b>25 de septiembre</b> fue acreditar a la primera entidad para certificar sistemas de gestión de compliance según la UNE-EN ISO 37301. Y la <b>EN 18286</b>, la norma europea de sistema de gestión de la calidad para fines del Reglamento de IA, se publicó en julio de 2026 pero <b>sigue sin estar citada en el DOUE</b>.",
 "Tres cosas que se pueden decir hoy con seguridad a un cliente. Una: si sus políticas o su Declaración de Aplicabilidad citan definiciones de la ISO/IEC 27000, están citando una edición retirada, y eso lo mira un auditor. Dos: quien venda «certificación ISO 42001 acreditada» en España no puede respaldarlo con acreditación de ENAC; la certificación existe, el esquema acreditado no, y conviene dejarlo por escrito en la propuesta. Y tres: publicada no es armonizada. Implantar la EN 18286 hoy da alineamiento técnico y ventaja de calendario, pero <b>no da presunción de conformidad</b>, porque para eso hace falta la cita en el Diario Oficial.",
 '<a href="https://www.iso.org/standard/27000" @L>Ficha de la ISO/IEC 27000</a> y la <a href="https://www.enac.es/que-hacemos/servicios-de-acreditacion/sistemas-de-gestion" @L>relación de esquemas de sistemas de gestión de ENAC</a>.',
 "Lo de la EN 18286 se ha verificado por la página de normalización de la Comisión y por CEN-CENELEC, no consultando directamente las series del DOUE: es «sin evidencia de cita», no «confirmada la ausencia». Y la lectura de las fichas de ISO no es fiable para movimientos internos de etapa, así que «sin cambios» tiene confianza media."),

("ai", "AEPD · 23 sep 2026", True,
 "La AEPD advierte a una empresa antes de que despliegue IA para puntuar currículums, y deja la lista de garantías por escrito",
 "El <b>23 de septiembre</b> la AEPD publicó que una empresa proyectaba implantar una herramienta de IA para analizar currículums, <b>asignar puntuaciones y priorizar candidatos</b> en contratación y movilidad interna, y que actuó <b>antes del despliegue</b>. La medida es una <b>advertencia del artículo 58.2.a</b> del RGPD, y la propia nota subraya que es una medida preventiva sobre tratamientos <b>previstos</b> y que <b>no supone declarar que se haya cometido infracción</b>; la herramienta no se había puesto todavía en funcionamiento. Las garantías que enumera: protección de datos desde el diseño y por defecto desde la configuración inicial; medidas técnicas y organizativas apropiadas con evaluación de riesgos para candidatos y trabajadores; evaluación de impacto previa si el tratamiento entraña alto riesgo; transparencia clara, accesible y comprensible sobre el tratamiento y sobre la función de la herramienta; e <b>intervención humana efectiva</b>, de modo que quien decida pueda valorar críticamente la puntuación y no se limite a asumirla automáticamente.",
 "Es el caso de uso de IA más extendido entre clientes medianos españoles, y el regulador acaba de publicar la lista de comprobación. Dos cosas se pueden hacer esta misma semana: una nota a clientes con la enumeración, y una plantilla de evaluación de impacto para selección de personal. Pero el titular útil es el precedente de método: <b>la Agencia entra antes del despliegue</b>, sobre un tratamiento que todavía no existe. Eso traslada el trabajo al diseño y convierte «lo miramos cuando esté en producción» en una postura cara. Y ataca el punto flojo habitual, que es la supervisión humana meramente formal: firmar lo que dice el sistema no es valorarlo críticamente.",
 '<a href="https://www.aepd.es/prensa-y-comunicacion/notas-de-prensa/agencia-recuerda-garantias-para-utilizar-ia-en-analisis-curriculums" @L>Nota de la AEPD del 23 de septiembre</a>.',
 "Cuidado con la terminología: es una <b>advertencia</b> del artículo 58.2.a, no un apercibimiento, que en la nomenclatura de la Agencia es el 58.2.b y presupone infracción ya cometida. Llamarlo sanción es incorrecto."),

("ai", "INCIBE-CERT · 24 sep 2026", False,
 "El CERT nacional lleva a su bitácora el primer ataque notificado en España ejecutado por un agente de IA",
 "El <b>24 de septiembre</b> el INCIBE-CERT publicó en su bitácora de seguridad la ficha del caso que la AEPD había contado el 14: un <b>agente de inteligencia artificial</b> buscó vulnerabilidades de forma autónoma en ficheros genéricos, logró autenticarse, examinó la aplicación por su cuenta, encontró un fallo que permitía <b>modificar datos personales</b> y accedió a <b>facturas</b>. El CERT deja igual de claro lo que no se sabe: no se revela la identidad de la entidad ni el sector, ni el número de personas afectadas, ni el volumen de información comprometida, y la AEPD sigue analizando la información aportada. Por separado, la <b>multa de 403 millones de euros</b> de la autoridad irlandesa a Google, del <b>21 de septiembre</b>, se basa en licitud y lealtad, responsabilidad proactiva, transparencia y conservación, y su decisión íntegra aún no está publicada.",
 "El cambio no es de hechos, es de nivel de fuente: que el CERT nacional lo documente convierte un caso de blog del regulador en material citable en un informe a dirección. Y hay un detalle que se pasa por alto y que decide dónde poner el dinero: lo relevante aquí no es la confidencialidad, es la <b>integridad</b>. Hubo modificación de datos, no solo robo, y casi ningún plan de respuesta contempla ese escenario, que en facturación es mucho más difícil de revertir y mucho más grave. La pregunta para el cliente es sencilla: si alguien alterase registros la semana pasada, cuánto se tardaría en detectarlo y cómo se probaría cuál era el valor correcto.",
 '<a href="https://www.incibe.es/incibe-cert/publicaciones/bitacora-de-seguridad/brecha-de-datos-notificada-en-espana-vinculada-un-ataque-ejecutado" @L>Bitácora del INCIBE-CERT del 24 de septiembre</a>.',
 "No es un incidente con nombre y apellidos, y por eso no está en la sección de incidentes: ni la AEPD ni el INCIBE-CERT identifican a la entidad ni al sector."),

("ai", "CEPD · consultas abiertas", False,
 "Tres consultas del CEPD siguen abiertas y la respuesta sobre la ISO/IEC 27701 continúa sin publicarse",
 "Sin plenario nuevo en la ventana. Siguen abiertas las consultas sobre <b>anonimización</b> y sobre <b>web scraping para IA generativa</b>, adoptadas el 8 de julio, hasta el <b>30 de octubre</b>, y la de las directrices sobre el ejercicio del poder de imponer multas frente a los demás poderes correctivos, adoptadas en el plenario del <b>21 de septiembre</b>, hasta el <b>13 de noviembre</b>; estas últimas traen una metodología de cinco pasos, catorce ejemplos prácticos y sustituyen a las directrices del antiguo Grupo del Artículo 29. En ese mismo plenario se adoptó la versión final de las directrices sobre la interacción entre el reglamento de servicios digitales y el RGPD. Lo que sigue sin aparecer es la <b>respuesta a la entidad alemana de acreditación</b> sobre el papel de la ISO/IEC 27701:2025 respecto del artículo 42.5 del RGPD.",
 "Las directrices de multas son el documento que dice cómo se va a leer el caso de un cliente que acaba de sufrir una brecha: cuándo la autoridad se queda en una advertencia o una orden de corrección y cuándo multa, y con qué cuantía. Hay hasta noviembre para que las asociaciones sectoriales opinen. Y sobre la 27701, mientras no se publique nada, la respuesta al cliente no cambia: certificarse en esa norma <b>no equivale</b> a un mecanismo de certificación aprobado del artículo 42, y prometerlo en una propuesta es un riesgo propio.",
 '<a href="https://www.edpb.europa.eu/news/news_en" @L>Noticias del CEPD</a>.',
 "Que la respuesta sobre la 27701 no esté publicada es «no se ha localizado»: los listados documentales del CEPD que sí se alcanzaron están claramente desactualizados respecto de su propia sección de noticias, así que no se puede afirmar que el texto no exista."),

("thr", "Citrix · 27 y 28 sep 2026", True,
 "Citrix confirma dos días cero explotados en NetScaler, y el catálogo KEV les pone el plazo más corto del año",
 "Boletín de Citrix del <b>27 de septiembre</b>: ocho vulnerabilidades en <b>NetScaler ADC</b> y <b>NetScaler Gateway</b>, de la <b>CVE-2026-88771</b> a la <b>CVE-2026-88778</b>. El propio fabricante escribe que «se han observado explotaciones de CVE-2026-88771 y CVE-2026-88772 en despliegues sin mitigar». La primera permite a un atacante <b>sin autenticar</b> ejecutar órdenes arbitrarias; la segunda es una operación fuera de los límites de un búfer de memoria, también sin privilegios previos. Afectan a la rama 14.1 por debajo de 14.1-73.37 y a la 13.1 por debajo de 13.1-64.23, más las variantes FIPS. Las dos entraron en el <b>catálogo KEV el 27</b> con fecha límite el <b>30 de septiembre</b>: tres días. Hoy, <b>28 de septiembre</b>, el INCIBE-CERT ha publicado el aviso <b>INCIBE-2026-667</b>, que recoge las ocho, tres de ellas críticas, y confirma la explotación de las dos primeras.",
 "NetScaler es la puerta: pasarela de acceso remoto, proxy y servidor virtual de autenticación. Ejecutar órdenes ahí no es comprometer un activo, es entrar en la red con las llaves. Esto justifica parcheo de emergencia y no ventana ordinaria, y con dos consecuencias que conviene decir en voz alta. La primera: parchear no cierra el caso. Si estuvo expuesto, hay que buscar compromiso, porque la directiva estadounidense que fija ese plazo de tres días exige triaje forense precisamente por eso, y aunque no obligue aquí, marca el listón de diligencia que mirará una auditoría. La segunda: si el equipo estuvo expuesto y se confirma intrusión, para una entidad esencial de NIS2 o una entidad financiera bajo DORA el reloj de las 24 horas de alerta temprana empieza a correr, así que el procedimiento de notificación tiene que estar a mano esta semana, no la que viene.",
 '<a href="https://support.citrix.com/external/article/CTX697096/citrix-netscaler-adc-and-citrix-netscale.html" @L>Boletín CTX697096 de Citrix</a> y el <a href="https://www.incibe.es/incibe-cert/alerta-temprana/avisos/multiples-vulnerabilidades-en-productos-de-citrix-1" @L>aviso INCIBE-2026-667</a>.',
 "El catálogo KEV consultado es la versión del 27 de septiembre, así que altas del 28 no figurarían todavía. Ninguno de los doce CVE añadidos esta semana consta con uso conocido en campañas de programas de secuestro."),

("thr", "Check Point, F5 y Arista · 22 y 23 sep 2026", True,
 "Tres perímetros más con explotación reconocida por el fabricante en la misma semana",
 "<b>Check Point</b>, aviso propio del <b>22 de septiembre</b>: la <b>CVE-2026-85102</b> es una validación incorrecta de certificado en el tratamiento de certificados de VPN de Security Gateway, ejecución remota <b>sin autenticación previa</b>, y el fabricante describe una oleada de intentos contra clientes a escala global <b>desde el 12 de septiembre</b>, con correcciones publicadas el 9; la <b>CVE-2026-93616</b> es un recorrido de directorios, también sin autenticación previa, en el servicio web de gestión, con explotación descrita como muy dirigida. <b>F5</b>: la <b>CVE-2026-94127</b>, desbordamiento de montículo sin autenticación en BIG-IP APM, con explotación confirmada por el fabricante, aviso <b>INCIBE-2026-662</b> del 23, y una mitigación temporal por regla del propio fabricante que permite ganar tiempo para el triaje. <b>Arista</b>: la <b>CVE-2026-93952</b> en VeloCloud Orchestrator local, validación incorrecta de entrada que da acceso a funciones internas privilegiadas sin credenciales, explotación confirmada por Arista, aviso <b>INCIBE-2026-656</b> del 23.",
 "Cuatro fabricantes de perímetro con explotación confirmada en una semana no es casualidad: es dónde está mirando el atacante. Y hay una trampa que cuesta cara. El aviso del INCIBE sobre Check Point, el <b>INCIBE-2026-657</b>, cubre <b>solo la CVE-2026-93616</b>. La que el fabricante describe como oleada global, la 85102, <b>no está en ese aviso</b>, así que quien priorice únicamente por el boletín nacional se deja fuera la peor de las dos. La regla operativa es la de siempre y esta semana se paga: el catálogo de avisos nacional es un buen filtro, no un inventario completo, y en producto de perímetro hay que ir al aviso del fabricante.",
 '<a href="https://www.incibe.es/incibe-cert/alerta-temprana/avisos/path-traversal-en-productos-de-check-point" @L>Aviso INCIBE-2026-657</a>, <a href="https://www.incibe.es/incibe-cert/alerta-temprana/avisos/desbordamiento-de-bufer-basado-en-monticulo-en-big-ip-apm-de-f5" @L>aviso INCIBE-2026-662</a> y <a href="https://www.incibe.es/incibe-cert/alerta-temprana/avisos/validacion-incorrecta-de-datos-de-entrada-en-velocloud-orchestrator-de-arista" @L>aviso INCIBE-2026-656</a>.',
 None),

("thr", "Catálogo KEV · 21 a 28 sep 2026", False,
 "Doce vulnerabilidades explotadas nuevas en una semana, y la de SharePoint no es la que circula",
 "El catálogo KEV sumó <b>doce</b> altas entre el <b>21 y el 28 de septiembre</b>. Además de las cuatro de perímetro ya citadas: <b>Microsoft SharePoint</b>, CVE-2026-65660, inyección de código, alta el 25; <b>WordPress</b>, CVE-2026-87902, inclusión remota de ficheros que afecta de la 4.7.0 a la 7.1.1 y se corrige en la 7.1.2, alta el 25, con aviso <b>INCIBE-2026-659</b> del 23; <b>MikroTik RouterOS</b>, CVE-2026-67279, encadenable para explotar sin autenticación otra vulnerabilidad ya catalogada, alta el 25; <b>Adobe Commerce y Magento</b>, CVE-2026-71362, autorización incorrecta, alta el 24; <b>WSO2</b>, CVE-2026-5430, recorrido de directorios hasta ejecución remota, alta el 24; y <b>Zyxel</b> GS1900, CVE-2026-7273, desbordamiento de pila, alta el 21. Ninguna de las doce consta con uso conocido en campañas de programas de secuestro.",
 "Dos precisiones que evitan decisiones equivocadas. La de SharePoint <b>no es sin autenticación</b>: la describen como explotable por un atacante <b>autorizado</b>, así que llegar a ejecución remota anónima exige encadenarla con un salto de autenticación aparte, y eso cambia mucho la urgencia relativa frente a Citrix o Check Point. Y en WordPress hay una discrepancia útil de conocer: el aviso del INCIBE del 23 <b>no menciona explotación</b>, y quien la afirma es el catálogo estadounidense al darla de alta el 25, dos días después. Prevalece lo posterior, pero conviene citar quién dice qué. En conjunto, el orden razonable de esta semana es Citrix primero, luego Check Point, después F5 y Arista, y solo entonces el resto.",
 '<a href="https://www.cisa.gov/known-exploited-vulnerabilities-catalog" @L>Catálogo KEV</a>.',
 "Las altas se han leído del fichero de datos del catálogo, versión del 27 de septiembre, no de la página web. Las puntuaciones que circulan para la de SharePoint no se han podido ver en la ficha del fabricante, así que no se dan."),

("thr", "Tecnología operativa · 21 y 22 sep 2026", False,
 "Semana floja en control industrial: solo dos avisos, y uno de ellos persiste al reinicio",
 "El listado de avisos de sistemas de control industrial del INCIBE-CERT recoge <b>solo dos</b> en la ventana, frente a los siete de la semana anterior. El del <b>22 de septiembre</b>, de criticidad <b>crítica</b>, es una inyección de saltos de línea en el cliente de VPN de <b>Lenze</b>, CVE-2026-75925: valores de configuración aceptados por el servicio local se escriben en un fichero que después consume un proceso con privilegios elevados, lo que permite ejecutar órdenes como administrador, y la configuración maliciosa <b>persiste tras el reinicio</b> manteniendo la VPN funcionando con normalidad. Afecta de la 1.0.0 a la 1.4.6 usadas con la pasarela x500 y se corrige en la 1.4.7. El del <b>21</b>, de criticidad alta, es una escritura fuera de límites en el conmutador TN-4500B de <b>Moxa</b>, CVE-2026-15579, denegación de servicio remota sin autenticación, etiquetado como ferrocarril. En ninguno consta explotación.",
 "El de Lenze merece atención por cómo falla, no por cuántos lo tienen. Una configuración maliciosa que sobrevive al reinicio y deja el túnel funcionando con normalidad es invisible a la comprobación operativa habitual, que es «reinicia y mira si conecta». Ese es justo el escenario que el plan de respuesta de un cliente industrial no suele contemplar. Y el de Moxa importa por el sector: ferrocarril es entidad esencial del anexo I de NIS2, y esta misma semana el panorama de ENISA sitúa al ferrocarril entre los sectores con madurez por debajo de la media y criticidad por encima.",
 '<a href="https://www.incibe.es/incibe-cert/alerta-temprana/avisos-sci" @L>Avisos de sistemas de control industrial del INCIBE-CERT</a>.',
 "El aviso de Lenze no especifica si la explotación requiere autenticación previa, así que no se dice. Se han revisado los listados y las dos fichas, no versiones afectadas de terceros productos."),
]

BULOS = [
 ("«El paquete de infracciones de septiembre incluye algo de NIS2 o de CER.»",
  "No. El INF/26/1834, de 25 de septiembre, se ha leído íntegro y no menciona NIS2, CER, DORA ni el CRA. Lo que sí trae para España, entre otros cinco bloques, es un emplazamiento por la sexta directiva antiblanqueo."),
 ("«El reglamento de calificación de centros de datos ya está publicado.»",
  "No. Se <b>adoptó</b> el 21 de septiembre y está en escrutinio de dos meses del Parlamento y el Consejo, que pueden objetar pero no enmendar. No consta en el DOUE. Corrección a la edición 005, que dijo «publicó»."),
 ("«Las directrices de la EBA sobre terceros no TIC ya tienen fecha de aplicación.»",
  "No. El informe final lleva marcadores de posición, «[fecha]», tanto para la aplicación como para la derogación de las de externalización de 2019. Sin esa fecha no se puede calcular el fin del transitorio de dos años. Sí tienen número: EBA/GL/2026/09."),
 ("«Adif y Renfe han confirmado el robo de 500 GB.»",
  "No. La cifra procede de fuentes citadas por un medio, y ambas entidades dicen que la forense sigue abierta. Renfe acota lo accedido a nombres y direcciones de correo. Tampoco han confirmado autoría ni que se usara IA."),
 ("«La AEPD ha sancionado a una empresa por usar IA para cribar currículums.»",
  "No. Es una <b>advertencia</b> del artículo 58.2.a sobre un tratamiento previsto y aún no puesto en marcha, y la propia nota dice que no supone declarar infracción. El apercibimiento es el 58.2.b y es otra cosa."),
 ("«El aviso del INCIBE sobre Check Point cubre las dos vulnerabilidades explotadas.»",
  "No. El INCIBE-2026-657 cubre solo la CVE-2026-93616. La que el fabricante describe como oleada global desde el 12 de septiembre es la CVE-2026-85102, y no está en ese aviso."),
 ("«La vulnerabilidad de SharePoint explotada esta semana es sin autenticación.»",
  "No. Se describe como explotable por un atacante <b>autorizado</b>. Para llegar a ejecución remota anónima haría falta encadenarla con un salto de autenticación aparte."),
 ("«ESMA retira su prioridad supervisora de ciberresiliencia.»",
  "No. La nueva prioridad de innovación digital, que arranca en 2027, corre en paralelo con la de ciberseguridad y resiliencia operativa, vigente desde 2025. La que se cierra este año es la de divulgación ambiental, social y de gobernanza."),
 ("«La multa de 403 millones a Google es un precedente del artículo 32.»",
  "No. Los incumplimientos son de licitud y lealtad, responsabilidad proactiva, transparencia y conservación, sobre datos de localización. La autoridad irlandesa no ha publicado todavía la decisión íntegra con el articulado."),
 ("«La EN 18286 ya da presunción de conformidad con el Reglamento de IA.»",
  "Sigue sin darla. Está publicada desde julio de 2026, pero no citada en el DOUE, y sin esa cita no hay presunción de conformidad."),
]

SILENCIO = [
 ("BOE", "Revisados íntegramente, por la interfaz de datos abiertos, los sumarios del 21, 22, 23, 24, 25, 26 y 28 de septiembre: ninguna disposición de ciberseguridad, ENS, entidades críticas, protección de datos o IA. Lo único adyacente son dos resoluciones de personal de la AESIA y un convenio de la Secretaría de Estado de Digitalización sobre IA en salud. Semana completa y alcanzable, por primera vez en varias ediciones."),
 ("Consejo de Ministros", "Revisada la referencia del 22 de septiembre, la única de la ventana. Nada del ámbito: Interior llevó asilo y extranjería, y Transformación Digital solo ofertas de empleo público."),
 ("Transposición de NIS2 en España", "Sin movimiento. El anteproyecto de coordinación y gobernanza de la ciberseguridad sigue donde quedó tras el Consejo de Ministros del 14 de enero de 2025: sin segunda vuelta, sin proyecto en las Cortes y sin medidas notificadas a la Comisión."),
 ("CCN-CERT", "Alcanzado solo por su canal oficial, porque la web sigue bloqueando el acceso automatizado. Un único mensaje en la ventana, el del 22 sobre las Jornadas STIC. Ninguna alerta de vulnerabilidad publicada por ese canal entre el 21 y el 28, ni siquiera la de Citrix del domingo."),
 ("INCIBE", "Una sola nota en la sala de prensa, del 24, sobre un evento divulgativo en Gran Canaria. Ninguna convocatoria ni documento estratégico. La sección de convocatorias devolvió error, así que ahí es «no alcanzado»."),
 ("AESIA", "Sin guía, criterio ni acto nuevo. Su última entrada es del 16 de septiembre. Lo único visible en el BOE es dotación de plantilla."),
 ("Portal de Administración Electrónica", "No alcanzado: bloqueo sistemático al acceso automatizado. Es el hueco que impide comprobar en su fuente natural las Instrucciones Técnicas de Seguridad, los Perfiles de Cumplimiento Específico y el fichero del ENS en formato legible por máquina."),
 ("Consejo de la Unión Europea", "No alcanzado: el registro público y la sala de prensa devolvieron acceso denegado toda la semana. El estado del paquete de NIS2 y del Reglamento de Ciberseguridad en el Consejo, y el del ómnibus digital, quedan cubiertos solo por el lado del Parlamento."),
 ("Tribunal de Justicia", "Revisados todos los avisos de acciones nuevas publicados en la ventana: ninguno de NIS2, CER, DORA ni CRA. Siguen pendientes de publicación los recursos de NIS2 decididos el 8 de julio, entre ellos el de España."),
 ("CRA y plataforma de notificación", "Sin novedad. La página de política de la Comisión sigue con última actualización del 7 de septiembre y las guías de ENISA, del 9 y 10. El censo de organismos notificados no se pudo consultar: el registro se ha migrado a una aplicación que no sirve listado legible."),
 ("Ómnibus digital y nube", "El ómnibus grande, el que modifica DORA y NIS2, sigue esperando decisión de comisión desde enero de 2026: ocho meses sin movimiento. De la propuesta de reglamento de desarrollo de la nube y la IA, nada nuevo en la ventana. Del esquema europeo de certificación de nube, nada desde el 10 de agosto."),
 ("Banco Central Europeo", "Sin carta nueva, sin consulta abierta y sin número de septiembre del boletín de supervisión. En la ventana hay tres intervenciones: la de la presidenta del Consejo de Supervisión del 22, y dos más en las que ciber aparece solo de pasada o no aparece. TIBER-EU sigue sin documentos de 2026 y su página no cita el reglamento delegado de pruebas dirigidas por amenazas."),
 ("Proveedores TIC críticos", "Sin designaciones ni bajas: siguen los 19 de la lista del 18 de noviembre de 2025. La actualización anual que prevé el artículo 31.8 tocaría hacia noviembre."),
 ("Banco de España, CNMV y DGSFP", "Nada de ciberseguridad ni de DORA en lo alcanzable. La sección de ciberseguridad de la CNMV no tiene nada de septiembre; su sala de prensa devolvió acceso denegado y las novedades de la DGSFP tampoco se pudieron abrir, así que para esas dos es «no alcanzado». No se localizó página válida de TIBER-ES."),
 ("Oficina de IA y normalización", "Sin noticias, actos de ejecución ni códigos nuevos entre el 21 y el 28. La Comisión sigue sin ninguna norma armonizada del Reglamento de IA citada en el DOUE. No se localizó publicada la lista consolidada de autoridades de vigilancia del mercado."),
 ("ISO/IEC y acreditación", "Sin cambios detectados en las fichas de la familia 27000 y de la 42000, con confianza media por la lectura automatizada. ENAC sigue sin esquema de la 42001."),
 ("Catálogo KEV", "Alcanzado esta semana, a diferencia de las dos anteriores: fichero de datos completo, versión del 27 de septiembre, con las doce altas de la ventana leídas una a una."),
]

counts = {k: 0 for k in SEC}
for it in ITEMS: counts[it[0]] = counts.get(it[0], 0) + 1
