# -*- coding: utf-8 -*-
"""Incidentes del periodo. REGLA DE ADMISION: solo entra lo confirmado por la
entidad afectada, un regulador o un CERT oficial. Lo reivindicado por atacantes
o solo publicado en prensa sin confirmacion se queda fuera."""

SECTORES = {
 "adm":  ("Administración pública", "#C62828"),
 "fin":  ("Banca y seguros",        "#00796B"),
 "tec":  ("Tecnología y defensa",   "#1565C0"),
 "tra":  ("Transporte y logística", "#6A1B9A"),
 "ene":  ("Energía y agua",         "#E65100"),
 "tel":  ("Telecomunicaciones",     "#00695C"),
 "san":  ("Sanidad",                "#AD1457"),
 "edu":  ("Educación e investigación", "#455A64"),
}
TIPOS = {
 "ran": ("Ransomware",             "#C62828"),
 "rgpd":("Brecha RGPD",            "#1565C0"),
 "cont":("Continuidad de negocio", "#E65100"),
 "sum": ("Cadena de suministro",   "#6A1B9A"),
 "acc": ("Acceso no autorizado",   "#AD1457"),
}

# (id, entidad, pais, sector, [tipos], fecha, estado, que_se_sabe, quien_confirma, url,
#  obligaciones, leccion)
INCIDENTES = [
("adif","Adif y Adif Alta Velocidad","España","tra",["acc","rgpd","sum"],
 "Detectado la noche del 24 de septiembre de 2026; confirmado el 25, webs restablecidas el 26 y comunicación a los afectados publicada en la semana del 28","Abierto, comunicación a los afectados publicada",
 "<b>Cambio de estado: Adif ha publicado en su web una comunicación a los afectados «de conformidad con el artículo 34 del Reglamento General de Protección de Datos».</b> Confirmado por Adif: hubo dos frentes, la <b>Plataforma de Licitación Electrónica</b>, «alojada en un entorno externo a Adif y gestionado por un proveedor de servicios», y <b>sistemas de gestión corporativa</b>. Las categorías van separadas por ámbito. De los licitadores: nombre y apellidos, DNI, NIE o NIF, datos de contacto e información de participación en licitaciones; del personal gestor, código de usuario o matrícula y, en determinados casos, el DNI. De los sistemas corporativos: datos del <b>personal actual y pasado de Adif y Adif Alta Velocidad, y de sus beneficiarios</b>, que podrían incluir información identificativa, de contacto, profesional, laboral, <b>económica</b>, <b>credenciales de acceso</b> y el resto de datos personales de las bases de datos de recursos humanos. Notificado a la <b>AEPD</b>, al <b>Centro Criptológico Nacional</b> y a las empresas y proveedores con posibilidad de verse afectados, con denuncia interpuesta. Canales abiertos para afectados. Desconocido: el número de personas afectadas, el volumen de datos, la identidad del proveedor de la plataforma, la autoría y si la forense está cerrada.",
 "Adif, en su propia web, en la página «Información sobre incidentes de ciberseguridad». Salvedad de lectura: la página no lleva fecha visible ni en el texto ni en los metadatos; su única referencia temporal es «los incidentes de la pasada semana».",
 "https://www.adif.es/informacion-incidente-ciberseguridad",
 "Artículo 33 del RGPD, ya cumplido ante la AEPD, y artículo 34, que es exactamente lo que materializa esta página. Ojo al censo: incluye extrabajadores y beneficiarios, lo que amplía mucho el universo de interesados. ENS de aplicación plena como entidad pública empresarial, con gestión del incidente y notificación al CCN-CERT, revisión del análisis de riesgos y de la Declaración de Aplicabilidad, y posible afectación a la conformidad vigente. Como operador crítico del subsector ferroviario, comunicación al CNPIC y revisión del Plan de Protección Específico. A efectos de NIS2 es entidad esencial del sector transporte, pero sin ley española de transposición el marco aplicable sigue siendo el RDL 12/2018 y el RD 43/2021. Y como la brecha entró por la plataforma de un tercero, se activa el régimen del artículo 28 del RGPD sobre el encargado, con auditoría y, en su caso, penalidades contractuales.",
 "Dos mensajes para llevar a cualquier cliente. El primero: el censo de interesados de una brecha de recursos humanos incluye <b>extrabajadores y beneficiarios</b>, y casi nadie lo tiene inventariado ni sabe a qué direcciones notificarles; eso se prepara antes, no durante. El segundo: una plataforma de licitación en modo servicio es un sistema del alcance del ENS y del de NIS2, no «una herramienta de compras», y conviene que el contrato con el encargado incluya <b>preservación y entrega de evidencias forenses</b>, porque aquí ha habido que pedirla después. Y una nota de rigor sobre cómo se lee el comunicado: Adif usa el condicional en todo momento, dice que «no se dispone de evidencia de un uso indebido de los datos» y advierte de que la enumeración «no significa que todas las personas se hayan visto afectadas». Es la forma correcta de comunicar con forense abierta."),

("renfe","Renfe Viajeros","España","tra",["acc","rgpd","sum"],
 "Acceso el 24 de septiembre de 2026; nota inicial el 25 y comunicación a los afectados y aviso a la plantilla en la semana del 28","Abierto, alcance ampliado respecto de la nota inicial",
 "<b>Cambio de estado doble, y es el hallazgo más consecuente de la semana en España.</b> Renfe ha publicado una página de notificación a las personas afectadas que <b>amplía materialmente</b> lo que anunció el 25 de septiembre. Texto literal de la notificación: «los datos potencialmente comprometidos podrían incluir datos identificativos y de contacto, así como información asociada a la utilización de los servicios de Renfe, <b>incluida información relativa a billetes adquiridos y viajes realizados</b>. Asimismo, entre la información potencialmente afectada <b>podrían encontrarse números de DNI, NIE u otros documentos identificativos equivalentes</b>, así como <b>credenciales de autenticación (contraseñas), protegidas mediante técnicas criptográficas de seguridad que impiden su lectura directa</b>». La nota del 25 de septiembre, en cambio, decía que los atacantes «pudieron acceder a información limitada de usuarios, consistente principalmente en nombres y direcciones de correo electrónico» y que «no existen evidencias de acceso a datos bancarios, financieros, medios de pago, <b>DNIs</b> u otra información especialmente sensible». El acceso se localiza en «determinados sistemas relacionados con los procesos de venta de billetes». Riesgos que Renfe reconoce por escrito: suplantación, fuerza bruta sobre contraseñas débiles reutilizadas y elaboración de perfiles de desplazamientos a partir del historial de viajes. Notificado a la <b>AEPD</b>, al <b>CCN</b>, a la Oficina de Coordinación de Ciberseguridad, al <b>CNPIC</b> y a la Guardia Civil, con solicitud de preservación de evidencias a proveedores y repositorios externos. Además, el <b>3 de octubre</b> Renfe comunicó a su plantilla el robo de datos laborales y profesionales y que la violación se ha notificado a la AEPD. Desconocido: número de clientes y de empleados afectados, algoritmo de resumen de las contraseñas y si llevan sal (determinante para el riesgo real), si hubo exfiltración efectiva o solo acceso, y la autoría.",
 "Renfe, en su propia web: la nota de prensa del 25 de septiembre, fechada y verificada, y la página de notificación a personas afectadas, que es la fuente de las categorías nuevas. El aviso a la plantilla del 3 de octubre es comunicación de la entidad por vía interna, con soporte público solo en prensa.",
 "https://www.renfe.com/es/es/ayuda/notificacion-personas-afectadas",
 "Artículos 33 y 34 del RGPD, ambos ya ejecutados. ENS y notificación al CCN-CERT. CNPIC como operador crítico. RDL 12/2018 y RD 43/2021 como marco de NIS1 vigente en España, con el sector transporte como esencial. Y, por el tipo de datos, revisión de la evaluación de impacto del tratamiento de venta de billetes: un historial de viajes es dato de comportamiento y de localización, lo que eleva el riesgo. La presencia de credenciales con resumen criptográfico obliga además a valorar el forzado de cambio de contraseña y la revocación de sesiones activas.",
 "Caso de libro de <b>comunicación en dos tiempos que se corrige a sí misma</b>, y la lección es dura y vendible: <b>en las primeras 72 horas no se descarta nada por categorías de datos</b>. Se describe lo verificado y se usa el lenguaje de «datos potencialmente afectados». Un desmentido prematuro, como el de los DNI, genera un segundo titular peor que el primero y, en sede de la AEPD, debilita la posición del responsable, porque obliga a explicar por qué se afirmó algo que la forense no sostenía. Formúlese ante el cliente como ampliación del alcance declarado, coherente con el propio aviso de Renfe de que la investigación sigue en curso, y no como ocultación: puede ser simplemente el avance del análisis. Segundo aprovechamiento: la interconexión entre dos entidades del mismo ecosistema demuestra que la <b>segmentación entre entidades</b> es un control de NIS2 y del ENS, no un detalle de arquitectura, y que hay que pactar por contrato quién notifica cuando el incidente empieza en la otra."),

("dgfip","Dirección General de Finanzas Públicas, la hacienda francesa","Francia","adm",["rgpd"],
 "Hechos de julio y agosto de 2026, detectados el 12 y 13 de agosto; informe oficial de la agencia nacional publicado el 29 de septiembre de 2026","Abierto, con informe oficial publicado y control del regulador en curso",
 "<b>Cambio de estado: por primera vez hay cifras y vectores oficiales, no estimaciones de prensa.</b> El <b>29 de septiembre</b> la agencia nacional francesa de ciberseguridad publicó su informe de incidente, entregado al primer ministro el 24. Dos incidentes. El primero, exfiltración de datos fiscales de cerca de <b>353.000 usuarios particulares</b> (estado civil, contacto, identificador fiscal, situación familiar, renta fiscal de referencia y tipo de retención) y <b>252.000 profesionales</b> (identificador de empresa, denominación y dirección). El segundo, en el servidor profesional de datos catastrales: una <b>cuenta comprometida de un geómetra experto de un gabinete privado</b>, que permitió sortear el segundo factor por correo, dio lugar a la exfiltración de unos <b>2 millones de datos catastrales</b> de aproximadamente <b>434.000 usuarios</b>, entre el 27 de julio y el 8 de agosto. Hubo además intentos de acceso con credenciales robadas por programas ladrones de información en equipos personales o de socios. La agencia pilota una revisión de las investigaciones y un plan de auditoría. La autoridad francesa de protección de datos mantiene abiertas sus verificaciones sobre la adecuación de las medidas, sin novedad desde el 18 de agosto. Desconocido: cierre de las investigaciones, sanciones y atribución definitiva.",
 "La agencia nacional francesa de ciberseguridad, en su informe de incidente propio, y la autoridad francesa de protección de datos sobre sus verificaciones.",
 "https://cyber.gouv.fr/actualites/lanssi-publie-le-rapport-dincident-sur-les-cyberattaques-ayant-touche-la-dgfip/",
 "Artículos 32, 33 y 34 del RGPD, con control abierto sobre la adecuación de las medidas. NIS2, transpuesta en Francia solo de forma parcial, con la agencia nacional ejerciendo potestad reforzada para imponer medidas de urgencia a los ministerios.",
 "Lo que hace este caso excepcionalmente útil es que la propia agencia nacional escribe que <b>no fue un ataque sofisticado</b>: segundo factor ausente o débil, parches tardíos y falta de segmentación. Eso desarma de raíz el argumento «nos atacó un actor avanzado, no había nada que hacer», que es el que más se oye en un comité tras un incidente. Y el vector concreto da la recomendación: cuando el acceso llega con <b>credenciales legítimas robadas en un equipo personal de un tercero habilitado</b>, el control que falla no es el perímetro, es la autenticación de accesos privilegiados y la detección del uso anómalo de una cuenta válida. Dos medidas que se venden solas con este caso: prohibir el acceso a aplicaciones sensibles desde dispositivos no gestionados, y revocar sesiones activas tras cualquier cambio de contraseña."),

("estadofr","Administración del Estado francés, incluidas la agencia nacional de ciberseguridad y la dirección interministerial de lo digital","Francia","adm",["rgpd","sum"],
 "Ola de incidentes desde el 1 de agosto de 2026; primer punto de situación oficial publicado el 30 de septiembre de 2026","Abierto, en seguimiento oficial periódico",
 "<b>Nuevo, y el documento más revelador de la semana.</b> El <b>30 de septiembre</b> el equipo de respuesta francés publicó el primer punto de situación de su operación de reacción reforzada: desde el <b>1 de agosto de 2026</b> se han puesto en su conocimiento <b>99 violaciones de datos</b>, de las cuales <b>67 están confirmadas</b> y 32 siguen en tratamiento. Vectores recurrentes identificados oficialmente: la vulnerabilidad <b>CVE-2026-72898 de Metabase</b>, una inyección SQL que da acceso a la base de datos sin autenticar y privilegios de administrador de la instancia, con <b>nueve instancias ministeriales comprometidas</b> y parche disponible desde el 6 de agosto; el robo de credenciales por programas ladrones de información; vulnerabilidades de referencia directa a objetos; la <b>ausencia de segundo factor o un segundo factor débil</b>, señalada como «factor clave de numerosos incidentes»; y la subcontratación y la cadena de suministro. El propio informe reconoce que la <b>agencia nacional de ciberseguridad fue comprometida</b>: 118 cuentas de usuario de Metabase en su laboratorio de innovación, de las cuales una treintena de usuarios externos, con identificadores, correos y contraseñas con resumen criptográfico expuestos. Y en la dirección interministerial de lo digital, dos instancias de Metabase comprometidas, con datos administrativos de organismos públicos que la propia dirección señala como ya públicos. Entre las demás entidades nombradas: el ministerio de Educación, con hasta 4,35 millones de docentes en un sistema y una base de alumnos de una academia; una mensajería institucional; un servicio de servicio nacional universal; el servicio antiblanqueo, por compromiso del <b>subcontratista</b> del operador de su módulo de asistencia, con cese de la relación con el prestador; y las aduanas.",
 "El equipo de respuesta nacional francés, en su punto de situación oficial.",
 "https://www.cert.ssi.gouv.fr/cti/CERTFR-2026-CTI-006/",
 "Artículos 32, 33 y 34 del RGPD ante la autoridad francesa. NIS2 para las administraciones públicas incluidas en su ámbito. Para el caso del servicio antiblanqueo, régimen del artículo 28 del RGPD y responsabilidad del subencargado, con la lección de que la cadena se rompió en el proveedor del proveedor.",
 "Es el mejor material de la semana para una conversación de consejo, con tres mensajes. Uno: <b>una sola vulnerabilidad en una herramienta de inteligencia de negocio comprometió nueve ministerios</b>. La pregunta para el cliente es cuántas instancias de Metabase, Grafana, Superset o similares hay en su organización, quién las expone a internet y quién las parchea; son la zona ciega típica, porque las despliega analítica o negocio, no el área de sistemas. Dos: la agencia nacional de ciberseguridad francesa fue comprometida por <b>una instancia sin parchear en su propio laboratorio de innovación</b>, que es el argumento definitivo contra los entornos de innovación, pruebas y laboratorios dejados fuera del alcance del sistema de gestión y del inventario de activos; extiéndase el alcance o aíslense de verdad, sometidos al mismo ciclo de parcheo. Y tres: el punto de situación tiene vocación de ser periódico, así que merece quedarse como fuente fija de seguimiento mensual. Es lo más parecido a un parte oficial de brechas de una administración europea que existe hoy."),

("viena","Ciudad de Viena, Magistrat der Stadt Wien","Austria","adm",["acc","rgpd"],
 "Acceso entre el 3 y el 11 de septiembre de 2026; aviso externo el 9, notificaciones el 10 y el 15, comunicado propio el 30 de septiembre","Contenido, afectados en notificación individual",
 "<b>Nuevo.</b> Confirmado por la Ciudad de Viena en comunicado propio: un atacante tuvo acceso, a través de un acceso web, a partes de una <b>plataforma interna de documentación del Magistrat</b> <b>entre el 3 y el 11 de septiembre de 2026</b>. Se copiaron en total unos <b>26.000 documentos y páginas</b>, con un volumen de datos de <b>unos nueve gigabytes</b>. Afectados, con desglose por colectivo: <b>2.885 ciudadanos, 2.083 empleados municipales y 856 contratistas</b> del Magistrat, a los que se notifica directamente en el plazo de una semana. El aviso no llegó de los controles internos: lo dio el <b>equipo de respuesta nacional austriaco el 9 de septiembre</b>, al detectar una oferta de venta de la vulnerabilidad en un foro en línea. El <b>10 de septiembre</b> la ciudad presentó una notificación de incidente <b>voluntaria</b> conforme a la ley austriaca de seguridad de redes, y el <b>15</b> la notificación legalmente prevista a la autoridad de protección de datos. La vulnerabilidad se cerró de inmediato. Según el conocimiento actual, los documentos no han sido publicados y la ciudad no ha sido extorsionada; su responsable de tecnología añade que el atacante «en ningún momento tuvo control sobre sistemas informáticos o cuentas de usuario». El comunicado advierte de que en áreas concretas pueden verse afectadas <b>categorías especiales de datos</b>. Desconocido: la naturaleza técnica exacta de la vulnerabilidad y la identidad del actor.",
 "La Ciudad de Viena, en comunicado propio de su oficina de prensa del 30 de septiembre, con declaraciones de su responsable de tecnología.",
 "https://presse.wien.gv.at/presse/2026/09/30/wien-datensicherheit-hat-hohen-stellenwert-sicherheitsluecke-umgehend-geschlossen",
 "Artículos 33 y 34 del RGPD ante la autoridad austriaca de protección de datos. Ley austriaca de seguridad de redes, con notificación ya presentada, en este caso de forma voluntaria. Conviene retener la fecha: el incidente es de septiembre, anterior a la entrada en vigor de la NISG 2026 el 1 de octubre, que es la que convierte la notificación en obligatoria.",
 "Tres cosas que un cliente puede copiar literalmente de este comunicado. Una: <b>cifras desglosadas por colectivo</b>, ciudadanos, empleados y contratistas, en lugar de un número global ambiguo. Dos: <b>cronología de notificaciones con fechas</b>, la de seguridad de redes el día 10 y la de protección de datos el 15, que es exactamente lo que un regulador quiere ver y lo que casi ningún comunicado español incluye. Tres: decir expresamente <b>qué no ha pasado</b>, que no hay publicación de datos ni extorsión, siempre acompañado de «según el conocimiento actual». Y una lección de detección que vale una propuesta: el aviso llegó de un equipo de respuesta nacional que vigilaba foros, no de los controles internos, lo que justifica un servicio de vigilancia digital."),

("dtu","Danmarks Tekniske Universitet","Dinamarca","edu",["acc","rgpd"],
 "Comunicado propio el 2 de octubre de 2026; fecha de detección y de inicio del acceso no publicadas","Abierto, investigación con especialistas externos",
 "<b>Nuevo.</b> Confirmado por la universidad: un ataque dirigido <b>comprometió perfiles de la propia institución</b> y los usó para acceder a <b>DTUBasen</b>, su sistema de gestión de identidad y de acceso, y descargar un volumen significativo de datos, con acceso a datos personales que se remontan a <b>2003</b>. Para los usuarios activos, la información puede incluir el <b>número de registro civil danés</b>, nombre completo, dirección, foto de perfil, correo de trabajo, puesto, ubicación de oficina y <b>nombre, relación y teléfono de familiares cercanos</b>. Para los antiguos usuarios, direcciones, fotos e información de familiares se borran automáticamente a los seis meses, pero la base sigue conteniendo <b>número de registro civil y nombre completo</b>. Alcance: la propia universidad dice que «no es posible determinar con precisión qué información se descargó ni cuántas personas se han visto afectadas», y precisa que la base contiene información de unos <b>40.000 usuarios activos</b> y unos <b>160.000 antiguos usuarios</b>. Notificado a la autoridad danesa de protección de datos y derivado a las autoridades competentes, con notificación individual a los afectados por el buzón electrónico oficial. Desconocido: fecha de detección y de inicio del acceso, vector inicial, autoría y cifra definitiva.",
 "La Universidad Técnica de Dinamarca, en nota propia del 2 de octubre.",
 "https://www.dtu.dk/english/newsarchive/2026/10/cyberattack-on-dtu_notification-of-a-personal-data-breach",
 "Artículos 33 y 34 del RGPD. El número de registro civil danés es identificador nacional, lo que eleva el riesgo y hace obligatoria la comunicación individual. NIS2 según el ámbito danés para el sector de investigación.",
 "El objetivo no fue una base de datos de negocio: fue el <b>sistema de identidades</b>. Comprometer el directorio da acceso lateral a todo lo demás y expone además a los usuarios históricos, que aquí son cuatro de cada cinco. Dos recomendaciones vendibles: una <b>política de baja y purga de identidades</b> con plazos de retención definidos y aplicados, que es justo lo que la universidad sí tenía para direcciones y fotos pero no para el identificador nacional; y tratar el sistema de identidades como activo de criticidad máxima, con segundo factor resistente a suplantación para las cuentas administrativas. Nota de honestidad editorial: la cifra de 200.000 es el <b>contenido de la base</b>, no una estimación de afectados, y la lista completa de datos solo aplica a los usuarios activos. Que la universidad admita que no puede cuantificar es la forma correcta de comunicar cuando no hay telemetría suficiente, y es a la vez el mejor argumento para invertir en registro de auditoría."),

("gutcert","GUTcert GmbH, certificadora de sistemas de gestión","Alemania","tec",["acc","sum"],
 "Exfiltración entre el 6 y el 9 de septiembre, detectada la noche del 9 al 10; comunicado propio del 21 de septiembre de 2026","Abierto, forense externa en curso",
 "<b>Caso resuelto: esta semana sí se ha podido leer el comunicado propio</b>, que la edición anterior no localizó y por el que el caso quedaba descartado. Confirmado por GUTcert: acceso no autorizado por terceros desconocidos y robo de datos por un volumen de <b>unos 640 gigabytes</b>, con exfiltración entre el 6 y el 9 de septiembre y detección la noche del 9 al 10. Notificado el <b>11 de septiembre</b> a la autoridad berlinesa de protección de datos, a la policía judicial del Land y a la oficina federal de seguridad de la información. <b>No se atendió el intento de extorsión.</b> Investigación forense externa en curso, con actualizaciones en un portal propio. Confirmado además por un cliente afectado, la eléctrica ENTEGA, el 24 de septiembre: se vieron afectados documentos presentados en el marco de su certificación, documentación del certificador y <b>nombres y datos de contacto de empleados</b>, pero no datos de clientes; la compañía afirma que la seguridad de suministro de su red de distribución «no se vio afectada en ningún momento», que notificó el incidente a la oficina federal como operador de infraestructura crítica y que ha contratado vigilancia de la red oscura. Desconocido: cuántos clientes certificados están afectados y qué hay exactamente en los 640 gigabytes.",
 "GUTcert, en comunicado propio publicado en su sala de prensa, y ENTEGA, en comunicado propio.",
 "https://www.pressebox.de/pressemitteilung/gut-certifizierungsgesellschaft-fuer-managementsysteme-mbh/cyberangriff-auf-die-gutcert-gmbh/boxid/1313139",
 "Artículos 33 y 34 del RGPD ante la autoridad de Berlín. Ley alemana de seguridad informática y NIS2 alemana para los clientes de infraestructura crítica que reciban notificación. Y, para cualquier cliente certificado por esta entidad, obligación de evaluar si una brecha en su <b>organismo de certificación</b> afecta a sus propios tratamientos y a su propia cadena de suministro, por el artículo 21.2.d de NIS2.",
 "Es el incidente de la semana con más valor comercial directo para un consultor de gobierno, riesgo y cumplimiento, porque hace visible algo que nadie tiene en el registro: <b>el auditor y el certificador son proveedores críticos con acceso a la documentación más sensible del cliente</b>, es decir declaraciones de aplicabilidad, análisis de riesgos, inventarios de activos, planes de continuidad, informes de auditoría y no conformidades. La pregunta para el cliente es si tiene a su organismo de certificación y a sus auditores externos en el registro de proveedores críticos, con evaluación de seguridad y cláusula de notificación de incidentes. Casi nadie los tiene. Y del lado de ENTEGA hay un ejemplo de comunicación de operador crítico que separa limpiamente lo corporativo de lo operativo, «la seguridad de suministro no se vio afectada en ningún momento», que es exactamente el mensaje que conviene tener redactado en el manual de respuesta antes de necesitarlo."),

("medyc","Qbusoft, desarrolladora de la plataforma sanitaria Medyc","Polonia","san",["rgpd","sum"],
 "Ataque de finales de agosto de 2026, descubierto el 9 de septiembre; inspección del regulador anunciada el 25 de septiembre y ampliada el 28","Abierto, con inspección del regulador en curso",
 "<b>Nuevo en la ventana por el lado regulatorio.</b> Confirmado por el regulador: el presidente de la autoridad polaca de protección de datos anunció una <b>inspección a Qbusoft</b>, desarrolladora del programa Medyc de gestión clínica, sobre sus medidas técnicas y organizativas, incluido el análisis de riesgos. La nota del regulador cifra los afectados en torno a <b>cinco millones de polacos</b> y encuadra el caso en una serie de fugas sanitarias, incluida otra de agosto de 2026 con cerca de diecinueve millones, con más de cincuenta reclamaciones y dos mil notificaciones de responsables recibidas hasta el 17 de septiembre. El presidente ha decidido <b>ampliar las inspecciones sobre tratamiento de datos de salud hasta finales de 2026</b>. Intervienen también el equipo de respuesta nacional y la oficina central de lucha contra la cibercriminalidad. Al menos un centro, un servicio público de tratamiento de adicciones y psiquiatría, ha reportado indicios de ejecución de guiones dirigidos a datos médicos, con afectación a pacientes atendidos entre julio de 2024 y agosto de 2026. Desconocido y expresamente no confirmado por la empresa: <b>Qbusoft no ha confirmado el robo de historiales médicos</b>, y la cifra de cinco millones procede del regulador, no de la compañía.",
 "La autoridad polaca de protección de datos, en nota propia. El incidente entra por vía de regulador; la entidad desarrolladora no lo ha confirmado.",
 "https://uodo.gov.pl/pl/138/4585",
 "Artículos 9, 32, 33 y 34 del RGPD: al tratarse de categorías especiales, el umbral de riesgo que obliga a comunicar a los interesados es bajo. Artículo 28: Qbusoft es encargada de los centros sanitarios, que siguen siendo los responsables y son quienes deben notificar y comunicar. NIS2 polaca, con la sanidad como sector esencial y el proveedor de software de gestión clínica dentro de la cadena de suministro.",
 "La lección es una que muchos clientes tienen al revés: en una brecha en el software de gestión clínica, <b>el obligado a notificar y a comunicar es cada centro sanitario, no el fabricante</b>. Recomendación operativa concreta para el contrato con el encargado: cláusula de notificación al responsable en <b>24 horas</b> desde que el encargado lo conoce, para que al responsable le queden cuarenta y ocho de las setenta y dos, y lista predefinida de responsables a los que el encargado debe avisar. Y un segundo aprovechamiento: que el regulador anuncie que amplía las inspecciones del sector hasta fin de año es un argumento de oportunidad para clientes sanitarios españoles, porque la AEPD sigue recibiendo todas sus notificaciones de categorías especiales en datos de salud."),

("drivewealth","Revolut, a través de su proveedor DriveWealth","Estados Unidos, con clientes en la Unión","fin",["sum","rgpd"],
 "Acceso durante dos días de principios de septiembre de 2026; divulgado el 25 de septiembre","Contenido, sin cifra de afectados",
 "Sin novedad sustantiva, y la pregunta pendiente sigue sin respuesta: <b>a 5 de octubre ninguna de las dos partes ha divulgado el número de afectados</b>. Se mantiene lo confirmado: Revolut dice en su propia página de ayuda que DriveWealth le informó de que un tercero accedió a datos de clientes alojados en sus sistemas, y que los sistemas, la infraestructura y las bases de datos principales de Revolut <b>no se vieron afectados</b>; tampoco se vieron comprometidas credenciales de acceso, datos de tarjeta, números de identificación fiscal, fechas de nacimiento ni documentos de identidad. DriveWealth atribuye el incidente a una campaña sofisticada de ingeniería social y sitúa los datos afectados en nombres, correos, direcciones postales, teléfonos e información de empleo. Para clientes europeos se trataría de registros históricos anteriores a la reestructuración del servicio de acciones estadounidenses, tras la cual se dejó de compartir datos con el proveedor. Sin evidencia de acceso a fondos. Desconocido: número de afectados, desglose por países, si hay clientes españoles y el contenido de las notificaciones de DORA.",
 "Revolut, en su propia página de ayuda, y DriveWealth en declaración recogida por medios especializados.",
 "https://help.revolut.com/help/more/security-and-fraud/drivewealth-security-incident/",
 "DORA, por ser Revolut entidad financiera y DriveWealth proveedor TIC: clasificación del incidente conforme a la norma técnica de clasificación, notificación inicial, intermedia y final a la autoridad competente, y registro de información del acuerdo contractual con evaluación de si soporta una función crítica o importante. Artículos 28 y 33.2 del RGPD: el encargado debe notificar al responsable sin dilación indebida, y el reloj de las setenta y dos horas del responsable corre desde que lo sabe él. Importante al informar al cliente: <b>las notificaciones de DORA no son públicas</b>, de modo que la ausencia de información no permite concluir nada sobre el cumplimiento.",
 "Es el segundo incidente de Revolut en un mes y ninguno por un fallo técnico propio. El caso demuestra el valor de dos controles concretos que casi nunca están: una <b>política de retención y supresión en el proveedor</b>, porque el daño europeo viene de datos históricos que el proveedor seguía conservando después de cesar la relación de tratamiento; y un <b>derecho de auditoría con obligación de notificación en plazos compatibles con DORA</b>, porque la entidad financiera depende de que su proveedor le avise para poder cumplir sus propios plazos. Y conviene señalar la asimetría reputacional, que es el argumento que mueve a un consejo: los titulares llevan el nombre de Revolut aunque sus sistemas no se tocaran."),

("villalba","Ayuntamiento de Collado Villalba","España","adm",["ran","cont"],
 "Detectado el 15 de septiembre de 2026; contención y localización de la vía de acceso comunicadas el 16 y el 17, recuperación completa el 20 y sede electrónica operativa el 21","Servicios restablecidos, sin novedad en la ventana",
 "Sin novedad localizada. Se mantiene lo confirmado por el propio Ayuntamiento en su comunicado del 17 de septiembre: recuperación progresiva y <b>sin constancia de filtración de datos personales</b>, si bien los especialistas continuaban verificando todos los sistemas, con coordinación de la Guardia Civil y de la Consejería de Digitalización de la Comunidad de Madrid. Y lo declarado por la alcaldesa el 21: hubo petición de rescate, se decidió <b>no pagar</b>, no se da la cuantía por el secreto de la investigación, y la infraestructura se recuperó por completo en cinco días. Desconocido: el grupo, la vía de entrada y el importe. No consta cifra de afectados ni notificación explícita a la AEPD en lo accesible.",
 "El propio Ayuntamiento, en comunicado publicado en su web, y la alcaldesa en declaraciones posteriores. Salvedad de esta semana: la web municipal bloquea el acceso automatizado, así que solo se ha podido leer el titular indexado de la nota y no se puede descartar que haya publicaciones posteriores.",
 "https://www.colladovillalba.es/-/el-ayuntamiento-de-collado-villalba-inicia-la-recuperaci%C3%B3n-progresiva-de-los-servicios-municipales-tras-contener-el-ciberataque",
 "ENS de aplicación plena, con gestión del incidente y notificación al CCN-CERT. Artículo 33 del RGPD si hay riesgo para las personas: que no haya constancia de fuga no exime de documentar la evaluación, y esa evaluación tiene que poder enseñarse.",
 "Sigue siendo el caso más vendible del trimestre para un cliente municipal: recuperar el cien por cien de la infraestructura en cinco días sin pagar. Pero el mérito no está en la respuesta, está en lo que había antes, que son copias de seguridad probadas. Y la decisión de no pagar se toma mejor por escrito y en frío, en una política aprobada, que de madrugada."),

("leiria","Comunidade Intermunicipal da Região de Leiria","Portugal","adm",["ran","cont"],
 "Detectado la madrugada del 15 de septiembre y comunicado el 16 de 2026","Contenido, sin novedad en la ventana",
 "Sin novedad localizada. Se mantiene lo confirmado: programa de secuestro en el servidor de correo que la comunidad intermunicipal presta a diez municipios, aislamiento del servidor, recuperación desde copia de seguridad y adelanto de la migración a correo en la nube, con solo un municipio desconectado por precaución. La entidad dice haberlo reportado a las autoridades en los términos previstos por la legislación vigente, sin especificar a cuál. Desconocido: si hubo extracción de datos de los buzones y qué grupo está detrás. No se ha localizado comunicado en la web propia de la entidad, ni nota del centro nacional de ciberseguridad ni de la autoridad portuguesa de protección de datos.",
 "El secretario ejecutivo de la comunidad intermunicipal, en declaraciones recogidas por la prensa regional y económica portuguesa.",
 "https://www.regiaodeleiria.pt/2026/09/comunidade-intermunicipal-da-regiao-de-leiria-alvo-de-ataque-informatico/",
 "Portugal tiene su ley de NIS2 en vigor desde el 3 de abril de 2026: si la entidad está en su ámbito, notificación al centro nacional con los plazos de veinticuatro y setenta y dos horas. Artículo 33 del RGPD si el acceso alcanzó buzones con datos personales, que en un servidor de correo municipal es lo probable.",
 "Un servicio compartido entre municipios es un punto único de fallo, y sirve para abrir la conversación en diputaciones y mancomunidades españolas que prestan correo o sede electrónica a varios ayuntamientos. Y un aviso: migrar de plataforma en plena crisis resuelve la urgencia, pero es el momento en que más fácil es dejar una configuración mal hecha."),

("clm","Junta de Castilla-La Mancha, ámbito educativo","España","adm",["acc","rgpd"],
 "Ataque de septiembre de 2026; confirmado por la Junta, sin novedad en la ventana","Contenido, sin cifra ni contenido confirmados",
 "Sin novedad en la ventana. Lo confirmado sigue siendo lo mismo: la dirección general competente en telecomunicaciones y ciberseguridad de la Junta confirma el ataque, dice haber activado los protocolos e informado «a las autoridades competentes y a las personas potencialmente afectadas». No consta nota propia en el portal de la Junta sobre este incidente. Lo reivindicado por el grupo atacante, en volumen y en contenido, <b>sigue sin verificar</b> y se mantiene fuera.",
 "La Junta de Castilla-La Mancha, por declaraciones de su dirección general competente recogidas por prensa especializada.",
 "https://www.escudodigital.com/ciberseguridad/castilla-la-mancha-confirma-el-ciberataque-de-panzer-que-reivindica-el-robo-de-datos-de-alumnos-y-familias.html",
 "ENS de aplicación plena, con notificación al CCN-CERT. Artículos 33 y 34 del RGPD, y con especial cuidado si hubiera datos de menores o de necesidades educativas especiales, que serían categorías especiales y elevarían el umbral de comunicación individual.",
 "Mientras la entidad no publique un comunicado propio con alcance, cada semana que pasa el relato lo construye el atacante. Es el argumento para convencer a un cliente público de que una página propia de incidentes de seguridad, con actualizaciones fechadas, no es exposición: es la única forma de recuperar el control del mensaje. Adif y Renfe acabaron haciéndolo; esta entidad, todavía no."),

("ancpi","Agencia Nacional de Catastro y Publicidad Inmobiliaria de Rumanía, plataforma e-Terra","Rumanía","adm",["ran","cont","rgpd"],
 "Ataque de julio de 2026; conclusiones oficiales del regulador nacional del 2 de septiembre y comparecencia en el Senado el 9","Recuperado, sin verificación posible esta semana",
 "<b>No verificable esta semana.</b> Existen comunicados oficiales del Gobierno rumano sobre el reinicio escalonado de la plataforma y sobre que la base de datos catastral no fue comprometida, pero <b>no se ha podido alcanzar ninguno de los dos dominios oficiales</b>, ni por herramienta de recuperación de páginas ni por acceso directo. No se puede afirmar si ha habido novedad en la ventana. Se mantiene lo ya confirmado en ediciones anteriores: el vector fue una versión muy desactualizada de un componente de gestión de identidades expuesto a través de la aplicación de pagos, con una vulnerabilidad crítica ya conocida; el atacante entró el 10 de julio y no se detectó hasta el 14, es decir tres días y catorce horas dentro; se exfiltraron ficheros de usuarios, equipos y grupos, y código fuente; y la plataforma se reconstruyó en la nube gubernamental.",
 "La autoridad nacional de ciberseguridad de Rumanía, en sus conclusiones oficiales del 2 de septiembre, y la comisión competente del Senado. Esta semana, fuente no alcanzable.",
 "https://www.cert.ro/",
 "Rumanía transpuso NIS2 por ordenanza de urgencia de diciembre de 2024: notificación al equipo de respuesta nacional y deberes de continuidad. Artículos 33 y 34 del RGPD por los registros de la plataforma.",
 "El caso sigue sirviendo para la misma conversación: un componente de gestión de identidades desactualizado y expuesto a internet a través de otra aplicación es el patrón exacto que esta semana ha vuelto a aparecer en la administración francesa con Metabase. Cuando el mismo patrón se repite en dos administraciones europeas en tres meses, deja de ser anécdota y pasa a ser un hallazgo que conviene buscar activamente en el inventario de cualquier cliente. Y de método: que no se pueda alcanzar la fuente oficial una semana es «no sé», no «no ha pasado nada»."),
]

DESCARTADOS = [
 ("AEMET", "Sigue solo reivindicada por el grupo Panzer desde el 11 de septiembre, con 5 GB y un ultimátum de veinte o veintiún días que vencía hacia el 1 o 2 de octubre. Comprobado esta semana: no hay nota en la web de la AEMET, ni comunicado del ministerio, ni aviso del CCN-CERT o del INCIBE-CERT, y tampoco consta que los datos se hayan publicado. Fuera, y con el aviso de que ausencia de confirmación no es desmentido."),
 ("Las cifras de 500 GB y de 150 millones de datos en Adif y Renfe", "Ninguna de las dos entidades ha confirmado volumen ni número de afectados, y ambas mantienen la forense abierta. Los incidentes entran; las cifras, no."),
 ("La autoría y el ángulo de la IA en Adif y Renfe", "Ni Adif ni Renfe mencionan IA en ninguna de sus comunicaciones, y la atribución a un grupo concreto sale de fuentes cercanas a la investigación recogidas por medios, no de las entidades ni del CCN. Fuera. Aviso de confusión, por si aparece en otras notas: la primera brecha ejecutada mediante un agente de IA que documentó la AEPD se notificó el 14 de septiembre, diez días antes del acceso a Adif, y no es este caso."),
 ("El número de afectados de DriveWealth y Revolut", "Sigue sin divulgarse por ninguna de las dos partes a 5 de octubre. El incidente entra; la cifra, no."),
 ("Hospital de la Santa Creu i Sant Pau, Barcelona", "Reivindicación detectada el 2 de octubre, sin especificar qué datos ni qué volumen. Sin confirmación del hospital, del departamento de salud autonómico ni de la agencia catalana de ciberseguridad. Dato llamativo: el hospital tiene una página propia de información sobre incidentes de seguridad que se renderiza con sello de actualización de hoy pero está vacía de contenido. Fuera, y es lo primero que hay que mirar la semana que viene."),
 ("Junta de Andalucía", "Reivindicación del 29 de septiembre, con ciento noventa y ocho direcciones de correo del dominio institucional y registros financieros, legales, técnicos y de recursos humanos. Sin confirmación de la Junta ni de su agencia digital. Fuera."),
 ("El volumen y el contenido reivindicados en Castilla-La Mancha", "El ataque sí está confirmado por la Junta y entra como ficha. El volumen y el contenido, incluidos censo escolar y expedientes de menores, son reivindicación pendiente de verificación. Fuera como cifra."),
 ("La cifra de 678.437 registros de la hacienda francesa", "Aparece en el anexo cronológico del propio informe oficial, pero como reivindicación del atacante y con un desglose distinto del que da el cuerpo del informe. Las cifras de 353.000 y 252.000 que sí se usan en la ficha son también las publicadas por el atacante, asumidas por el informe. No se suman los conjuntos y no se da por cerrado el recuento."),
 ("La cifra de 48 millones de propietarios en un servicio francés de vivienda vacía", "El propio informe oficial lo formula en condicional y el incidente está en investigación, con la base aislada preventivamente. El incidente queda cubierto en la ficha de la administración francesa; la cifra, fuera."),
 ("La publicación en la red oscura de los datos de un organismo belga de formación el 4 de octubre", "El incidente subyacente sí está confirmado por el propio organismo en su web, pero su nota no cuantifica afectados ni menciona notificación a la autoridad. La republicación del 4 de octubre, con más de setecientas mil personas y más de ochenta y cinco mil cuentas bancarias, procede de un sitio privado de seguimiento de filtraciones recogido por prensa, sin confirmación del organismo, de la autoridad belga de protección de datos ni del centro nacional. Y hay discrepancia de fechas sin aclarar entre la nota propia y la prensa. Fuera el hecho nuevo."),
 ("Venta de dieciocho millones de registros de jugadores de un videojuego", "Venta en red oscura del 4 de octubre sin confirmación del titular. Fuera."),
 ("Operador ferroviario japonés y dos casos estadounidenses y japoneses más", "Fuera del ámbito geográfico europeo, aunque el ferroviario japonés sirve como contexto comparable al de Adif y Renfe si alguien lo pide."),
 ("La advertencia de la AEPD sobre IA en el cribado de currículums", "No es un incidente: es una medida preventiva del artículo 58.2.a) sobre un tratamiento previsto y no implantado. Va en la sección de IA y datos."),
]

LAGUNAS = (
 "Seis avisos sobre lo que <b>no</b> aparece aquí. Primero, y es la laguna más importante de la edición: <b>el INCIBE-CERT no ha sido alcanzable</b> en toda la ventana, porque su cortafuegos de aplicación bloquea sistemáticamente el acceso automatizado en todas las rutas, incluida la raíz del sitio. No hay por tanto recuento de avisos de seguridad ni de avisos de sistemas de control industrial de esta semana, y eso es «no se ha podido leer», no «no hay». "
 "Segundo, <b>banca y seguros no dieron ningún incidente europeo nuevo confirmado</b>, solo el seguimiento de Revolut y su proveedor, y eso es en parte un artefacto del marco: las notificaciones de incidentes graves de DORA a las autoridades competentes <b>no son públicas</b>, igual que no lo son las del MUS. Con un cliente financiero conviene decirlo así, porque ausencia de noticias no es ausencia de incidentes. "
 "Tercero, <b>telecomunicaciones, energía y agua, defensa, industria y retail no dieron ningún incidente nuevo confirmado</b> de entidad europea. En energía el único vector es indirecto, el de la certificadora alemana hacia su cliente eléctrico. Y en telecomunicaciones no se han localizado notificaciones públicas bajo la Ley 11/2022 ni resoluciones de la secretaría de estado competente: es probablemente «no hay nada público», no «no hay nada». "
 "Cuarto, <b>ninguna sanción firme nueva por el artículo 32 del RGPD en España</b> se ha localizado, pero el buscador de resoluciones de la AEPD no se ha podido ordenar por fecha de publicación, así que es «no encontrado», no «no hay». Las dos resoluciones relevantes de la semana en la Unión son italiana e irlandesa, y van en la sección de IA y datos. "
 "Quinto, <b>dos fuentes oficiales no alcanzables</b> además del INCIBE-CERT: los dominios del Gobierno rumano y de su agencia de catastro, y la web municipal de Collado Villalba, las tres por bloqueo al acceso automatizado. En esos tres frentes no se puede afirmar que no haya novedad. "
 "Y sexto, una salvedad de método propia: <b>ni la comunicación de Adif ni la de Renfe llevan fecha visible</b> ni sello de última actualización. Es un defecto de las propias notas, y un problema para que las entidades acrediten el cumplimiento del plazo del artículo 34. Conviene señalárselo a cualquier cliente que publique una página de este tipo: una comunicación sin fecha no sirve como evidencia."
)
