# -*- coding: utf-8 -*-
"""Mapa de cuadricula de la UE-27 por norma. Codificacion compuesta:
color + simbolo + etiqueta, para que sea legible con daltonismo (rojo y verde
estan a delta-E 4.1 en deuteranopia, asi que el color NO puede ir solo)."""

EST = {  # clave: (etiqueta, color, simbolo, relleno)
 "completa": ("Traspuesta o en vigor", "#0ca30c", "&#10003;", "solido"),
 "parcial":  ("Parcial o pendiente",   "#fab219", "&#9680;", "rayado"),
 "ninguna":  ("Sin medidas",           "#ec835a", "&#8211;", "hueco"),
 "tjue":     ("Remitido o demandado ante el TJUE","#d03b3b", "&#10007;", "solido"),
 "desc":     ("Sin dato público",      "#898781", "?",        "hueco"),
}

REJILLA = [
 [None,None,None,None,None,"FI",None],
 [None,None,"IE",None,"SE","EE",None],
 [None,None,None,"DK",None,"LV",None],
 [None,None,"NL","DE","PL","LT",None],
 [None,"BE","LU","CZ","SK",None,None],
 ["PT","ES","FR","AT","HU","RO",None],
 [None,None,"IT","SI","HR","BG",None],
 [None,None,"MT",None,"GR","CY",None],
]
PAIS = {"BE":"Bélgica","BG":"Bulgaria","CZ":"Chequia","DK":"Dinamarca","DE":"Alemania",
 "EE":"Estonia","IE":"Irlanda","GR":"Grecia","ES":"España","FR":"Francia","HR":"Croacia",
 "IT":"Italia","CY":"Chipre","LV":"Letonia","LT":"Lituania","LU":"Luxemburgo","HU":"Hungría",
 "MT":"Malta","NL":"Países Bajos","AT":"Austria","PL":"Polonia","PT":"Portugal","RO":"Rumanía",
 "SI":"Eslovenia","SK":"Eslovaquia","FI":"Finlandia","SE":"Suecia"}

NORMAS = [
 ('nis2','NIS2','Directiva (UE) 2022/2555','directiva',
  'Transposición nacional obligatoria. El plazo venció el 17 de octubre de 2024. El color dice si hay ley nacional que ya obligue a las empresas; el procedimiento de infracción va aparte.',
  'Veintitrés Estados tienen ley en vigor, y solo dos no tienen ni ley ni proyecto en las Cortes: Irlanda no ha publicado siquiera su proyecto y España sigue en anteproyecto desde enero de 2025. Austria tiene la ley publicada pero no entra en vigor hasta el 1 de octubre de 2026. La Comisión decidió el 8 de julio de 2026 remitir al Tribunal de Justicia a cuatro Estados: Irlanda, España, Francia y Países Bajos, este último con ley en vigor desde el 15 de agosto pero sin que la Comisión haya cerrado el expediente. A 15 de septiembre no hay ningún recurso NIS2 registrado: la decisión de remitir no es el recurso. Y ojo al dato que confunde: tener expediente abierto no significa no haber transpuesto. Ocho Estados con ley en vigor, y Austria con la suya publicada, siguen en fase de dictamen motivado, mientras la Comisión ha cerrado ya once expedientes.<br><br><b>¿Quién llega antes?</b> Austria, seguro: el 1 de octubre de 2026. Después, previsiblemente Francia, con el proyecto a punto de pleno y procedimiento acelerado, hacia el primer trimestre de 2027. Irlanda y España van detrás: Irlanda todavía no ha presentado el proyecto, y España ni siquiera lo ha llevado al Consejo de Ministros en segunda vuelta. En España el único atajo realista es un real decreto-ley. Pasa el ratón por cada país para ver su previsión. <i>Previsión propia, revisada el 22 de septiembre de 2026.</i>'),
 ('cer','CER','Directiva (UE) 2022/2557','directiva',
  'Transposición nacional obligatoria. El plazo venció el 17 de octubre de 2024 y la identificación de entidades críticas, el 17 de julio de 2026. Bajo esta directiva las obligaciones de cada entidad nacen cuando el Estado la identifica y se lo notifica.',
  'Veintitrés Estados tienen ley en vigor, y casi todas obligan por fases: el capítulo de resiliencia se aplica a cada entidad diez meses después de que el Estado la identifique y se lo notifique, y la identificación debía estar hecha el 17 de julio de 2026, cosa que muy pocos Estados han hecho pública. Sin ley: España, con proyecto en el Congreso; Suecia, con proposición en el Riksdag y entrada en vigor propuesta para enero de 2027; Francia, con el proyecto atascado en la Asamblea; y Bulgaria, con un borrador que no ha salido de consulta pública. Aquí el procedimiento va por delante que en NIS2: hay ya seis recursos interpuestos con número de asunto, entre ellos el de España, el C-616/26 de 8 de junio de 2026. Luxemburgo fue remitido el 29 de abril pero la Comisión aplazó la remisión el 8 de julio tras notificar su ley. Y un dato que no hay que leer mal: la Comisión no ha cerrado ningún expediente CER, ni siquiera de Estados con ley en vigor desde 2024.<br><br><b>¿Quién llega antes?</b> Suecia, previsiblemente el 1 de enero de 2027. Francia, con el mismo proyecto que NIS2, hacia el primer trimestre de 2027. España, en el primer semestre de 2027 si deja de prorrogar las enmiendas. Bulgaria, la última: su proyecto ni siquiera ha pasado por el Consejo de Ministros. Pasa el ratón por cada país para ver su previsión. <i>Previsión propia, revisada el 22 de septiembre de 2026.</i>'),
 ('dora','DORA','Reglamento (UE) 2022/2554','reglamento',
  'Aplicable directamente en los 27 desde el 17 de enero de 2025. Lo que varía es el régimen sancionador nacional del capítulo VII.',
  'España tiene carta de emplazamiento desde julio de 2026 por no notificar el régimen sancionador. El proyecto 121/000105 no es solo retraso interno: es un procedimiento de infracción vivo.'),
 ('ia','Reglamento de IA','Reglamento (UE) 2024/1689','reglamento',
  'Aplicable directamente en los 27. Lo que varía es la designación de autoridades nacionales, que debía notificarse antes del 2 de agosto de 2025.',
  'La lista oficial de la Comisión lleva congelada desde septiembre de 2025 con solo ocho países. El reparto de aquí procede de un rastreador que cubre los 27 y está más actualizado.'),
 ('cra','CRA','Reglamento (UE) 2024/2847','reglamento',
  'Aplicable directamente en los 27. Lo que varía es la designación de autoridades de vigilancia del mercado y notificantes.',
  'Las obligaciones de notificación arrancaron el 11 de septiembre de 2026 y ENISA desplegó ese mismo día su plataforma. Lo que sí está completo es otra cosa: los 27 Estados tienen CSIRT coordinador designado, y el español es el INCIBE-CERT. Sigue sin haber ningún organismo notificado en toda la UE y la Comisión no publica censo de autoridades de vigilancia del mercado, de ahí que este mapa siga en su mayoría sin dato público.'),
]

# Datos por país portados de la edición 004 publicada (el generador de esa edición no llegó al repositorio).
D = {
"nis2": {
 'BE':('completa','Obliga desde el 18 de octubre de 2024, el mismo día que fijaba la directiva. Registro ante el Centro de Ciberseguridad y primera evaluación de conformidad antes del 18 de abril de 2026. Sin expediente de infracción.'),
 'BG':('completa','En vigor, pero el régimen sustantivo depende de actos pendientes: designación de autoridades y metodología en seis meses, ordenanza de medidas en ocho e identificación de entidades cinco meses después. Sanciones reducidas a la mitad por infracciones hasta el 1 de junio de 2026. Expediente: dictamen motivado.'),
 'CZ':('completa','En vigor desde el 1 de noviembre de 2025. Notificación del servicio regulado en 60 días; medidas de seguridad y notificación de incidentes exigibles como máximo un año después de la decisión de registro. Expediente cerrado por la Comisión.'),
 'DK':('completa','Obliga desde el 1 de julio de 2025. Registro hasta el 1 de octubre de 2025. Energía y telecomunicaciones tienen leyes sectoriales propias. Expediente cerrado por la Comisión.'),
 'DE':('completa','Obliga desde el 6 de diciembre de 2025, al día siguiente de su publicación. Registro ante el BSI en tres meses, hasta el 6 de marzo de 2026 para las entidades que ya lo eran. Expediente: dictamen motivado.'),
 'EE':('completa','En vigor desde el 1 de enero de 2026. Comunicación de datos al RIA en tres meses, hasta el 1 de abril de 2026; adaptación plena a los requisitos en tres años, hasta el 1 de enero de 2029. Expediente: dictamen motivado.'),
 'IE':('tjue','Ni ley ni proyecto publicado: no figura en el registro del Oireachtas. El Gobierno preveía publicarlo en otoño de 2026 y notificar antes de fin de año. Sigue el marco de 2018. Expediente: remisión al TJUE decidida.<br><br><b>¿Cuándo se espera?</b> No antes del primer semestre de 2027. El esquema general se publicó el 30 de agosto de 2024, pero el texto del proyecto sigue sin presentarse; según un despacho irlandés, continúa en la lista de publicación prioritaria del otoño de 2026. Publicarlo es solo el principio: faltan todas las fases en las dos cámaras.<br><b>Qué lo movería:</b> La presentación del proyecto en el Dáil este otoño.<br><b>Qué vigilar:</b> El registro de proyectos del Oireachtas y la fecha de la segunda lectura. Ojo: CER sí está transpuesta en Irlanda desde 2024, por reglamento. <i>Previsión propia, revisada el 22 de septiembre de 2026.</i>'),
 'GR':('completa','Obliga desde su publicación. Registro de entidades ante la Autoridad Nacional de Ciberseguridad en dos meses, hasta el 27 de enero de 2025. Modificada por la Ley 5256/2025 en diciembre. Expediente cerrado por la Comisión.'),
 'ES':('tjue','Sin ley ni proyecto en las Cortes: el anteproyecto lo aprobó el Consejo de Ministros en primera vuelta el 14 de enero de 2025 y no ha vuelto a moverse. Siguen rigiendo el RDL 12/2018 y el RD 43/2021. Cero medidas notificadas. Expediente: remisión al TJUE decidida.<br><br><b>¿Cuándo se espera?</b> Por ley ordinaria, no antes de 2027, y con riesgo de no llegar. Le faltan la segunda vuelta en el Consejo de Ministros, el dictamen del Consejo de Estado, que no consta, y toda la tramitación en las Cortes, que para una ley de este tamaño rara vez baja de seis a nueve meses. En octubre o noviembre de 2026 está prácticamente descartado. Y si las Cortes se disuelven antes de aprobarla, el texto decae: el mandato vence el 23 de julio de 2027.<br><b>Qué lo movería:</b> Un real decreto-ley, como el RDL 12/2018 con el que España transpuso tarde la primera NIS. No hay información oficial de ninguno en preparación, pero la remisión al Tribunal de Justicia con petición de multa es justo el tipo de presión que lo provoca, y un real decreto-ley entra en vigor al día siguiente de publicarse.<br><b>Qué vigilar:</b> La referencia del Consejo de Ministros de cada martes, que es donde aparecería la segunda vuelta o un real decreto-ley; la entrada del proyecto en el BOCG, serie A; y el Plan Anual Normativo. En marzo de 2026 el Gobierno solo dijo que la tramita Interior, sin fecha. <i>Previsión propia, revisada el 22 de septiembre de 2026.</i>'),
 'FR':('tjue','Sin ley. El Senado lo aprobó el 12 de marzo de 2025 y la comisión especial de la Asamblea Nacional informó el 10 de septiembre de 2025; desde entonces, sin sesión pública. Sigue rigiendo el marco de 2018. Las quince medidas notificadas son textos anteriores a 2023. Expediente: remisión al TJUE decidida.<br><br><b>¿Cuándo se espera?</b> Lo más probable, en el primer trimestre de 2027, con diciembre de 2026 como mejor caso. El proyecto tiene procedimiento acelerado desde octubre de 2024, así que tras el voto de la Asamblea pasa a una comisión mixta paritaria, no a segunda lectura. El canal parlamentario LCP sitúa el inicio del examen en pleno al final de la segunda semana de octubre de 2026, compartiendo semanas con el presupuesto; el orden del día oficial todavía no lo recoge.<br><b>Qué lo movería:</b> Que la Conferencia de Presidentes lo fije en el orden del día. Lo frenarían la saturación presupuestaria, una moción de censura o una disolución.<br><b>Qué vigilar:</b> El orden del día de la Asamblea Nacional y, tras el voto, la convocatoria de la comisión mixta paritaria. <i>Previsión propia, revisada el 22 de septiembre de 2026.</i>'),
 'HR':('completa','En vigor desde febrero de 2024. Las obligaciones de cada entidad nacen con la notificación de su categorización, con un año para implantar las medidas desde esa notificación. Reglamento de desarrollo en vigor desde el 30 de noviembre de 2024. Sin expediente de infracción.'),
 'IT':('completa','En vigor desde el 16 de octubre de 2024, con obligaciones diferidas: notificación de incidentes nueve meses después de la comunicación de la agencia nacional a cada entidad y medidas de gestión de riesgos dieciocho meses después; el artículo 30 desde el 1 de enero de 2026. Sin expediente de infracción.'),
 'CY':('completa','En vigor desde su publicación. Las entidades esenciales se identifican por evaluación de criticidad de la autoridad digital, notificada a cada una. Expediente cerrado por la Comisión.'),
 'LV':('completa','Obliga desde el 1 de septiembre de 2024. Autoevaluación hasta el 1 de abril de 2025, lista de sujetos el 17 de abril, responsable de ciberseguridad y primer informe hasta el 1 de octubre de 2025. Expediente cerrado por la Comisión.'),
 'LT':('completa','Obliga desde el 18 de octubre de 2024. El centro nacional debía inscribir a los sujetos antes del 17 de abril de 2025; los requisitos se implantan en un plazo no inferior a doce meses desde la inscripción. Expediente cerrado por la Comisión.'),
 'LU':('completa','Obliga desde el 10 de mayo de 2026. Registro ante el ILR o el HCPN en dos meses, hasta el 10 de julio de 2026. Deroga la ley de 2019. Expediente cerrado por la Comisión.'),
 'HU':('completa','Obliga desde el 1 de enero de 2025. Registro en 30 días desde que la entidad entra en el ámbito, inventario en 90, clasificación en 120 y política de seguridad en 180. Primera auditoría antes del 31 de diciembre de 2025 para las ya inscritas. Expediente: dictamen motivado.'),
 'MT':('completa','La orden se publicó en abril de 2025 con la vigencia diferida a aviso ministerial, que fijó el 23 de enero de 2026 para todas sus disposiciones. Sin escalonamiento posterior. Expediente cerrado por la Comisión.'),
 'NL':('tjue','Obliga desde el 15 de agosto de 2026, sin derecho transitorio: unas 8.000 organizaciones con notificación en 24 horas desde el primer día. Registro nacional constituido antes del 15 de septiembre de 2026. Expediente: remisión al TJUE decidida.'),
 'AT':('parcial','Publicada pero no en vigor: el § 51 la hace entrar el primer día del mes siguiente a nueve meses de la publicación, el 1 de octubre de 2026. Hasta entonces rige la ley de 2018. Registro de entidades en los tres meses siguientes, hasta el 1 de enero de 2027. Expediente: dictamen motivado.<br><br><b>¿Cuándo se espera?</b> Ya tiene fecha: entra en vigor el <b>1 de octubre de 2026</b>. Desde ese día notificar incidentes es obligatorio, aunque el registro pueda hacerse hasta el 1 de enero de 2027. Es el único cambio seguro del mapa en las próximas semanas. <i>Previsión propia, revisada el 22 de septiembre de 2026.</i>'),
 'PL':('completa','En vigor desde el 3 de abril de 2026, con doce meses para cumplir las medidas y la notificación, hasta el 3 de abril de 2027; inscripción en el registro hasta el 3 de octubre de 2026; las multas no pueden imponerse hasta el 3 de abril de 2028. Expediente: dictamen motivado.'),
 'PT':('completa','En vigor desde el 3 de abril de 2026 y reglamento desde el 23 de junio. Autoidentificación en la plataforma del centro nacional; las medidas de los artículos 27 a 30 y 33 despliegan efectos veinticuatro meses después de la reglamentación, hacia junio de 2028. Expediente: dictamen motivado.'),
 'RO':('completa','Obliga desde el 31 de diciembre de 2024, con sanciones desde el 30 de enero de 2025. Registro ante el DNSC en 30 días. Expediente cerrado por la Comisión.'),
 'SI':('completa','En vigor desde el 19 de junio de 2025. Autorregistro hasta el 19 de diciembre de 2025; medidas de gestión de riesgos hasta el 19 de diciembre de 2026, o el 19 de junio para los antiguos operadores esenciales. Expediente cerrado por la Comisión.'),
 'SK':('completa','Obliga desde el 1 de enero de 2025. Notificación a la NBÚ en 60 días. Los antiguos operadores pueden seguir con las medidas anteriores hasta el 31 de diciembre de 2026. Expediente cerrado por la Comisión.'),
 'FI':('completa','Obliga desde el 8 de abril de 2025. Registro en un mes y modelo de gestión de riesgos en tres. Åland tiene ley propia desde el 1 de septiembre de 2025. Expediente: dictamen motivado.'),
 'SE':('completa','Obliga desde el 15 de enero de 2026 sin fases diferidas. Registro en cuanto sea posible y notificación de incidentes en 24 o 72 horas. Expediente: dictamen motivado.'),
},
"cer": {
 'BE':('completa','En vigor desde su publicación. Las obligaciones dependen de la designación sectorial, que debía hacerse antes del 17 de julio de 2026; las infraestructuras críticas de la ley de 2011 pasan automáticamente a entidades críticas y conservan sus obligaciones anteriores hasta el 17 de mayo de 2027. Expediente: dictamen motivado.'),
 'BG':('tjue','Sin ley: el borrador del Ministerio del Interior no consta adoptado por el Consejo de Ministros ni presentado a la Asamblea. La Comisión afirma que no ha transpuesto ninguna medida. Recurso con petición de 2.284,8 euros diarios a tanto alzado y 12.303,36 de multa coercitiva. Expediente: recurso interpuesto ante el TJUE.<br><br><b>¿Cuándo se espera?</b> Primer semestre de 2027, o más tarde. El proyecto del Ministerio del Interior salió a consulta pública en mayo y junio de 2025; el programa legislativo del Gobierno preveía llevarlo al Consejo de Ministros en junio de 2026 y no consta que se hiciera. Bulgaria ya está demandada, asunto C-497/26, y en agosto de 2026 el Gobierno aprobó su posición ante el Tribunal.<br><b>Qué lo movería:</b> Que el Consejo de Ministros apruebe el proyecto y lo remita a la Asamblea Nacional.<br><b>Qué vigilar:</b> El orden del día semanal del Consejo de Ministros búlgaro y la entrada del proyecto en la Asamblea. <i>Previsión propia, revisada el 22 de septiembre de 2026.</i>'),
 'CZ':('completa','En vigor desde el 19 de agosto de 2025. Nadie es sujeto crítico automáticamente: solo por decisión del Ministerio del Interior, que debía dictar las primeras antes del 17 de julio de 2026; obligaciones diez meses después de la notificación. Expediente: carta de emplazamiento.'),
 'DK':('completa','En vigor desde el 1 de julio de 2025. Solo obliga a las entidades identificadas por decisión ministerial, con evaluación de riesgos a los nueve meses; el plazo de identificación venció el 17 de julio de 2026 y las notificaciones estaban en curso. Expediente: carta de emplazamiento.'),
 'DE':('completa','En vigor desde el 17 de marzo de 2026. Sin acto de identificación: el operador se autoidentifica por umbrales y debía registrarse antes del 17 de julio de 2026; evaluación de riesgos nueve meses después del registro y medidas, plan y notificación de incidentes a los diez. Expediente: dictamen motivado.'),
 'EE':('completa','La directiva se integra en el régimen de proveedores de servicios vitales. Quien ya cumplía las condiciones es proveedor desde el 18 de octubre de 2024 sin acto administrativo y debía tener plan conforme antes del 31 de diciembre de 2026; los nuevos, por designación. Sin expediente de infracción.'),
 'IE':('completa','En vigor desde el 17 de octubre de 2024, publicado en el boletín el 25. Identificación antes del 17 de julio de 2026, evaluación de riesgos a los nueve meses de la notificación y medidas a los diez. Estrategia nacional 2026 a 2029 publicada. Sin expediente de infracción.'),
 'GR':('completa','En vigor desde su publicación. La Secretaría General de Protección de Entidades Críticas identifica antes del 17 de julio de 2026 y el capítulo de obligaciones se aplica diez meses después de la notificación. No consta identificación completada. Expediente: dictamen motivado.'),
 'ES':('tjue','Sin ley. Proyecto publicado el 27 de marzo de 2026, en la Comisión de Interior por competencia legislativa plena, con el plazo de enmiendas ampliado semana a semana; la última, recogida en el cuadro del 22 de septiembre, lo lleva al 30 de septiembre de 2026. Sigue rigiendo la Ley 8/2011. Recurso con petición de 34.129,20 euros diarios a tanto alzado o un mínimo de 7.943.000, más 183.781,44 diarios de multa coercitiva. Expediente: recurso interpuesto ante el TJUE.<br><br><b>¿Cuándo se espera?</b> En el primer semestre de 2027 si el plazo de enmiendas se cierra de verdad; en 2026, muy difícil. Después de las enmiendas quedan la ponencia y la Comisión de Interior, en el mejor caso entre octubre y diciembre, los dos meses del Senado y la vuelta al Congreso si el Senado introduce cambios. Como va por competencia legislativa plena, el Pleno no interviene salvo enmienda de totalidad.<br><b>Qué lo movería:</b> Que el plazo deje de prorrogarse y se constituya la ponencia. Lo que la frena es visible: las ampliaciones semanales que arrastra desde abril, que son la señal de bloqueo, y el fin de la legislatura en 2027.<br><b>Qué vigilar:</b> El cuadro de plazos de enmiendas del Congreso, que se actualiza varias veces por semana; el orden del día de la Comisión de Interior; y el BOCG, donde se publicarían las enmiendas y el informe de la ponencia. <i>Previsión propia, revisada el 22 de septiembre de 2026.</i>'),
 'FR':('tjue','Sin ley: es el mismo proyecto que transpone NIS2, atascado en la Asamblea Nacional desde septiembre de 2025. Solo vincula el régimen de operadores de importancia vital del código de la defensa. Las 22 medidas notificadas son textos preexistentes. Expediente: recurso interpuesto ante el TJUE.<br><br><b>¿Cuándo se espera?</b> Con el mismo proyecto que NIS2: lo más probable, en el primer trimestre de 2027, con diciembre de 2026 como mejor caso. Procedimiento acelerado, examen en pleno previsto por el canal parlamentario LCP para la segunda quincena de octubre de 2026 y comisión mixta paritaria después.<br><b>Qué lo movería:</b> Que la Conferencia de Presidentes fije la fecha. Lo frenarían el presupuesto, una moción de censura o una disolución.<br><b>Qué vigilar:</b> El orden del día de la Asamblea Nacional y la convocatoria de la comisión mixta paritaria. <i>Previsión propia, revisada el 22 de septiembre de 2026.</i>'),
 'HR':('completa','En vigor desde el 21 de junio de 2025. Las obligaciones empiezan con la decisión gubernamental de confirmación de cada sujeto, con nueve meses para la evaluación de riesgos; hasta entonces sigue vigente la decisión de infraestructuras críticas de marzo de 2024. Expediente: carta de emplazamiento.'),
 'IT':('completa','En vigor desde el 18 de octubre de 2024. La lista de sujetos críticos se aprueba por decreto del presidente del Consejo antes del 17 de julio de 2026 y no se publica; obligaciones diez meses después de la notificación. Estrategia nacional adoptada el 30 de abril de 2026. Sin expediente de infracción.'),
 'CY':('completa','Norma reglamentaria, no ley primaria, en vigor desde su publicación. Identificación por la autoridad de defensa civil antes del 17 de julio de 2026 y obligaciones diez meses después de la notificación. Expediente: dictamen motivado.'),
 'LV':('completa','En vigor desde el 28 de junio de 2025 y reglamento desde el 16 de enero de 2026. Identificación administrativa clasificada por categorías dentro del sistema nacional preexistente; sin lista pública. Expediente: dictamen motivado.'),
 'LT':('completa','En vigor desde el 15 de noviembre de 2024. El Gobierno aprueba la lista de entidades de especial importancia, prevista antes del 16 de mayo de 2026, y el centro de gestión de crisis notifica los requisitos y la fecha desde la que se aplican. Expediente: carta de emplazamiento.'),
 'LU':('tjue','En vigor desde el 10 de mayo de 2026. Designación por decreto granducal, no publicada; el capítulo de obligaciones se aplica diez meses después de la notificación. La Comisión decidió remitirlo al Tribunal el 29 de abril y aplazó esa remisión el 8 de julio, tras la notificación de la ley. Expediente: remisión al TJUE decidida y aplazada.'),
 'HU':('completa','Parte sustantiva en vigor desde el 1 de enero de 2025. Designación por resolución de la autoridad competente, con responsable de resiliencia en 90 días y plan en el plazo que fije la resolución. Procedimientos en marcha, sin conclusión pública. Expediente: carta de emplazamiento.'),
 'MT':('completa','En vigor desde el 23 de enero de 2026. Las obligaciones nacen con la identificación y notificación en un mes; medidas diez meses después. La orden no fija plazo de identificación y no consta que se haya completado. Expediente: dictamen motivado.'),
 'NL':('tjue','En vigor desde el 15 de agosto de 2026. Deber de cuidado y de notificación diez meses después de la designación; primeras designaciones dentro del mes siguiente a la entrada en vigor, hasta el 15 de septiembre de 2026. Expediente: recurso interpuesto ante el TJUE.'),
 'AT':('completa','Las disposiciones estatales rigen desde el 17 de octubre de 2025 y el grueso de la ley desde el 1 de marzo de 2026. Las obligaciones nacen con la resolución de clasificación del Ministerio del Interior, que se esperaba a lo largo de 2026: evaluación de riesgos a los nueve meses y medidas a los diez. Expediente: dictamen motivado.'),
 'PL':('tjue','En vigor desde el 4 de julio de 2026. Primera identificación e inscripción en nueve meses, hacia abril de 2027; evaluación de riesgos nueve meses después de la notificación y medidas tres meses después. Hasta entonces sigue el régimen anterior. Expediente: recurso interpuesto ante el TJUE.'),
 'PT':('completa','Sin artículo de entrada en vigor, así que rige la regla supletoria del quinto día. Designación de entidades críticas antes del 17 de julio de 2026, con nueve meses para la evaluación y diez para el plan desde la notificación; hasta entonces siguen los planes del régimen de 2022. Expediente: carta de emplazamiento.'),
 'RO':('completa','En vigor desde el 2 de diciembre de 2024. La lista de entidades críticas se aprobó por decisión del primer ministro el 23 de julio de 2026; obligaciones diez meses después de la notificación y evaluación de riesgos a los nueve. Expediente: carta de emplazamiento.'),
 'SI':('completa','En vigor desde el 18 de diciembre de 2024. El Gobierno designa los sujetos críticos antes del 17 de julio de 2026 y estos elaboran el plan en nueve meses; hasta la designación sigue aplicándose la ley anterior. Expediente: carta de emplazamiento.'),
 'SK':('completa','En vigor desde el 1 de enero de 2025. Identificación por primera vez antes del 17 de julio de 2026; hasta entonces subsisten las designaciones de la ley anterior. Evaluación de riesgos a los nueve meses y plan a los diez desde la notificación. Expediente: carta de emplazamiento.'),
 'FI':('completa','En vigor desde el 1 de julio de 2025. Las obligaciones nacen con la decisión de identificación del ministerio competente, que debía dictarse antes del 17 de julio de 2026; el Ministerio del Interior anunció el 7 de julio que los ministerios la estaban completando. Expediente: dictamen motivado.'),
 'SE':('tjue','Sin ley. La proposición entró en el Riksdag el 14 de julio de 2026, con plazo de mociones hasta el 13 de octubre y entrada en vigor propuesta para el 1 de enero de 2027; las obligaciones se aplicarían diez meses después de cada decisión de identificación, no antes de finales de 2027. Expediente: recurso interpuesto ante el TJUE.<br><br><b>¿Cuándo se espera?</b> Lo más probable, el <b>1 de enero de 2027</b>. La proposición 2025/26:303 está en la Comisión de Defensa del Riksdag, con plazo de mociones hasta el 13 de octubre de 2026; para llegar a esa fecha lo normal es votar en noviembre o diciembre.<br><b>Qué lo movería:</b> El dictamen de la comisión. Lo retrasaría la formación de gobierno tras las elecciones generales suecas de septiembre.<br><b>Qué vigilar:</b> El dictamen de la Comisión de Defensa y la fecha de votación en el pleno del Riksdag. <i>Previsión propia, revisada el 22 de septiembre de 2026.</i>'),
},
"dora": {
 'BE':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'BG':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'CZ':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'DK':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'DE':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'EE':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'IE':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'GR':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'ES':('parcial','Carta de emplazamiento de julio de 2026 por no notificar el régimen sancionador. Las autoridades operan por el artículo 46, pero no hay sanciones.'),
 'FR':('parcial','Ninguna medida comunicada. Los supervisores actúan por el artículo 46, pero falta régimen sancionador.'),
 'HR':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'IT':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'CY':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'LV':('parcial','Transpuso la directiva de acompañamiento pero no notificó el capítulo VII del Reglamento.'),
 'LT':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'LU':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'HU':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'MT':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'NL':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'AT':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'PL':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'PT':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'RO':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'SI':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'SK':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'FI':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
 'SE':('completa','Medidas nacionales del capítulo VII notificadas a la Comisión.'),
},
"ia": {
 'BE':('ninguna','Sin designar. Se espera el regulador de telecomunicaciones según el acuerdo de coalición.'),
 'BG':('ninguna','Sin designar. El ministerio de gobernanza electrónica solo coordina.'),
 'CZ':('parcial','Propuesta legislativa sin aprobar.'),
 'DK':('completa','Ley 467, en vigor desde agosto de 2025. Agencia Danesa de Administración Digital.'),
 'DE':('parcial','Proyecto aprobado por el Gabinete en febrero de 2026, pendiente de las cámaras.'),
 'EE':('ninguna','Sin designar.'),
 'IE':('completa','Reglamento de 2025 con quince organismos designados y oficina nacional prevista.'),
 'GR':('ninguna','Sin designar. Proyecto esperado para junio de 2026.'),
 'ES':('parcial','AESIA designada y notificada, pero la ley orgánica que le da competencias formales sigue pendiente.'),
 'FR':('parcial','Autoridad de consumo como coordinadora, con propuesta de modelo descentralizado de más de doce autoridades.'),
 'HR':('ninguna','Sin designar.'),
 'IT':('completa','Ley 132/2025, en vigor desde octubre. Primer Estado con ley nacional de IA.'),
 'CY':('completa','Comisionado de Comunicaciones como autoridad de vigilancia, notificante y punto de contacto.'),
 'LV':('parcial','Centro de protección del consumidor como punto de contacto; notificante solo recomendada.'),
 'LT':('completa','Autoridad reguladora de comunicaciones y agencia de innovación.'),
 'LU':('parcial','Autoridad de protección de datos propuesta; proyecto de ley sin aprobar.'),
 'HU':('completa','Decreto gubernamental 344/2025.'),
 'MT':('completa','Autoridad de innovación digital como vigilancia y notificante.'),
 'NL':('parcial','Proyecto de abril de 2026 con diez autoridades sectoriales propuestas.'),
 'AT':('ninguna','Sin designar. Se espera una mesa de ayuda de IA en el regulador de telecomunicaciones.'),
 'PL':('parcial','Ley aprobada por la cámara baja en junio de 2026, pendiente del Senado.'),
 'PT':('parcial','Regulador de comunicaciones anunciado, notificante sin identificar.'),
 'RO':('parcial','Regulador de comunicaciones propuesto en marzo de 2026.'),
 'SI':('completa','Legislación nacional en vigor desde noviembre de 2025.'),
 'SK':('parcial','Oficina para la integridad digital como coordinadora.'),
 'FI':('completa','Ley 1377/2025, en vigor desde enero de 2026. Modelo descentralizado.'),
 'SE':('parcial','Autoridad de correos y telecomunicaciones propuesta como coordinadora.'),
},
"cra": {
 'BE':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'BG':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'CZ':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'DK':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'DE':('parcial','Proyecto de aplicación aprobado por el Consejo de Ministros federal en abril de 2026, con el BSI designado. No en vigor.'),
 'EE':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'IE':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'GR':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'ES':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'FR':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'HR':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'IT':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'CY':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'LV':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'LT':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'LU':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'HU':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'MT':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'NL':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'AT':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'PL':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'PT':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'RO':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'SI':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'SK':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
 'FI':('completa','Ley nacional de ciberresiliencia en vigor desde el 1 de junio de 2026, con autoridad de vigilancia y notificante designadas.'),
 'SE':('desc','Ni la Comisión ni ENISA publican designaciones por país.'),
},
}

for k in D:
    assert len(D[k]) == 27, (k, len(D[k]))
    for c in D[k]: assert c in PAIS, (k, c)
print("mapa: 5 normas x 27 países, datos completos")
for nid, nom, _, tipo, _, _ in NORMAS:
    from collections import Counter
    c = Counter(v[0] for v in D[nid].values())
    print(f"  {nom:18s} {tipo:10s}", dict(c))
